# -*- coding: utf-8 -*-
"""liuye_service.schemas — Pydantic re-export + 5 BFF-only cross-cutting protocols.

Per W1-backend brief §3 file 4 + v3 spec §2.5 + liuye_service/CLAUDE.md §3.

This module is **not** the SSOT for the 5 core Liuye contract protocols.
Those live in ``liuye_service/protocols/generated.py`` (auto-generated by
contract worker via ``datamodel-code-generator`` from
``shared/contracts/liuye/schemas/*.json``). We **re-export** them so
backend code can import everything from one place and downstream changes
do not ripple.

**Hard rule**: do NOT define ``LiuyeChatEvent`` / ``Artifact`` / ``ToolCall`` /
``KBDoc`` / ``EvidenceRef`` here. Contract worker owns them. Any reshape
must go through the JSON Schema → regen cycle so frontend Zod stays in
lockstep.

The 5 **BFF-only** cross-cutting protocols below come from v3 §2.5 — they
sit outside the 5 core protocols because they are control-plane envelopes
the BFF emits / consumes, not artifact payloads frontend renders.

1. ``LedgerReviewEvent``  — append-only review event (v3 §2.5 + 必修 #30/#69)
2. ``PermissionRequest``  — the "BFF emits" mirror of ``PermissionRequestEventPayload``
3. ``ValidationIssue``    — input validation failure descriptor (v3 §2.5)
4. ``ArtifactAction``     — UI action registry entry (v3 §2.5)
5. ``TokenBudgetState``   — token usage snapshot (v3 §2.5)
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, List, Literal, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr

# ---------------------------------------------------------------------------
# 1. Re-export the 5 core protocols from contract worker output
# ---------------------------------------------------------------------------
# Contract worker SSOT · do NOT shadow these here.
from liuye_service.protocols.generated import (  # noqa: E402, F401
    # Liuye 5-protocol members (per v3 §2.1-2.4)
    Artifact,
    ArtifactPatch,
    EvidenceRef,
    KBDoc,
    LiuyeChatEvent,
    ProgressMessage,
    ToolCall,
    # The two payloads we'll narrow in BFF code (v3 §2.1 line 56-82)
    PermissionRequestEventPayload,
    TurnErrorPayload,
)


# ---------------------------------------------------------------------------
# 2. BFF cross-cutting protocols (v3 §2.5 · NOT in contract worker SSOT)
# ---------------------------------------------------------------------------


class _LiuyeBaseModel(BaseModel):
    """Shared config — alias compatibility with generated models."""

    model_config = ConfigDict(
        # Mirror generated.py — accept either snake_case or alias name. Keeps
        # frontend Zod (camelCase) and backend Python (snake_case) interop
        # cheap without bespoke alias maps.
        populate_by_name=True,
        extra="forbid",
    )


class LedgerReviewEvent(_LiuyeBaseModel):
    """Append-only ledger review event (v3 §2.5 + 必修 #30/#69).

    Emitted when a reviewer (审贷员 / 合规官) acts on an existing
    ``decision_ledger`` entry. NEVER mutates the original decision row —
    instead pushed as a new event tied to ``decision_id``. This keeps the
    audit chain tamper-evident.

    Routing: ``POST /api/liuye/ledger/decisions/{decision_id}/review_events``
    → ``liuye_service/ledger_review.py`` handler.
    """

    event_id: constr(min_length=1) = Field(
        ...,
        description="Stable, idempotent event id (uuid4 · server-mint preferred). Frontend MAY set for double-submit dedup.",
    )
    decision_id: constr(min_length=1) = Field(
        ...,
        description="The decision_ledger entry this review targets. Tie via shared.decision_ledger.get_decision(decision_id).",
    )
    reviewer_id: constr(min_length=1) = Field(
        ...,
        description="User id of the reviewer (审贷员 / 合规官). Audited against persona/RBAC role at the endpoint.",
    )
    action: Literal["approve", "reject", "request_changes", "sign_off"] = Field(
        ...,
        description="Review verdict. sign_off = LE-05 high-risk signature · 必修 #21 idempotency_key required.",
    )
    comment: Optional[constr(min_length=1)] = Field(
        None,
        description="Free-form 中文 comment (reviewer reasoning). Required when action=reject/request_changes/sign_off.",
    )
    idempotency_key: constr(min_length=1) = Field(
        ...,
        description="Required on all review events · prevents double-submit (per v3 必修 #21 + #69).",
    )
    signature: Optional[constr(min_length=1)] = Field(
        None,
        description="Optional · digital signature blob (PKCS#7 / base64) for LE-05 sign_off. NULL for approve/reject.",
    )
    appended_at: AwareDatetime = Field(
        default_factory=lambda: datetime.now().astimezone(),
        description="ISO 8601 UTC · server-stamped when event is persisted. Frontend value (if any) is ignored.",
    )


class PermissionRequest(_LiuyeBaseModel):
    """BFF-side mirror of v3 §2.5 PermissionRequest (NOT the SSE payload).

    Difference vs ``PermissionRequestEventPayload`` (in ``generated.py``):

    - ``PermissionRequest`` is the **server-side state object** that
      ``permissions.py`` holds while waiting for grant/deny from the
      frontend. The orchestrator parks SSE business events while a
      ``PermissionRequest`` is unresolved.
    - ``PermissionRequestEventPayload`` is the **wire envelope** the BFF
      emits as the 11th SSE event ``permission.request``.

    Field shape MUST stay parallel so ``emit_permission_request(request)``
    can serialize ``request.model_dump(mode='json')`` directly into the
    payload (PM 2026-05-11 ratify · direct emit · NOT via SSE v1 adapter).
    """

    id: constr(min_length=1) = Field(
        ...,
        description="Stable PermissionRequest id (uuid4) · echoed as PermissionRequestEventPayload.request_id.",
    )
    risk_tier: Literal["low", "medium", "high"] = Field(
        ...,
        description="3-tier risk per v3 §2.5 · drives UI form-factor (low=inline · medium=modal · high=drawer).",
    )
    action: constr(min_length=1) = Field(
        ...,
        description="Backend canonical action id (e.g. 'credit_decision_submit' / 'ledger_write'). NOT a display label.",
    )
    idempotency_key: constr(min_length=1) = Field(
        ...,
        description="Required on all irreversible actions (high) · prevents double-execution.",
    )
    required_persona: Optional[List[constr(min_length=1)]] = Field(
        None,
        description="RBAC required persona list (backend-driven · frontend MUST NOT hardcode role names).",
    )
    disabled_reason: Optional[constr(min_length=1)] = Field(
        None,
        description="When current persona lacks required role · UI shows greyed-out button with explicit reason text.",
    )
    reason_required: Optional[bool] = Field(
        None,
        description="High-risk drawer requires user to type a reason before grant button enables.",
    )
    rule_source: Optional[constr(min_length=1)] = Field(
        None,
        description="Audit trace · which policy emitted this request (e.g. 'policy.rbac' / 'policy.ledger_write').",
    )
    scope: Optional[Literal["once", "session", "always"]] = Field(
        None,
        description="Grant scope · UI defaults to 'once' for high-risk.",
    )
    explanation: Optional[constr(min_length=1)] = Field(
        None,
        description="Human-readable 中文 explanation shown in confirmation UI.",
    )
    consequences: Optional[List[constr(min_length=1)]] = Field(
        None,
        description="Enumerated consequences shown as bullet list in high-risk drawer.",
    )
    # BFF internal bookkeeping · not echoed in the wire payload
    turn_id: Optional[constr(min_length=1)] = Field(
        None,
        description="BFF-internal · turn this request is parked under. Orchestrator uses for resume/abort.",
    )
    tool_call_id: Optional[constr(min_length=1)] = Field(
        None,
        description="BFF-internal · ToolCall this request blocks (if any).",
    )


class ValidationIssue(_LiuyeBaseModel):
    """One field-level validation failure (v3 §2.5).

    Returned in REST 4xx bodies + ``turn.error`` payload ``details`` when
    input validation fails before reaching an Agent. Error codes mirror
    the Zod inputSchemas error codes (contract worker SSOT) so frontend
    can render i18n messages without backend coupling.
    """

    field: constr(min_length=1) = Field(
        ...,
        description="Dotted JSON pointer into the request body (e.g. 'segment.preset_name').",
    )
    code: constr(min_length=1) = Field(
        ...,
        description="Machine-readable error code · matches Zod inputSchemas.ts error code enum.",
    )
    message: constr(min_length=1) = Field(
        ...,
        description="中文 human-readable message · shown next to the field in form UI.",
    )
    expected: Optional[Any] = Field(
        None, description="Optional · expected value/shape (e.g. enum members)."
    )
    actual: Optional[Any] = Field(
        None, description="Optional · the value we received (echoed for diagnosis)."
    )


class ArtifactAction(_LiuyeBaseModel):
    """UI action registry entry (v3 §2.5).

    The frontend renders artifact-bound buttons (e.g. 'Submit Decision',
    'Export to DOCX', 'Sign Off') by querying this registry — backend
    owns the canonical action ids + risk tier + persona gating. Frontend
    MUST NOT hardcode the action set.
    """

    action_id: constr(min_length=1) = Field(
        ...,
        description="Stable canonical action id (e.g. 'credit_decision_submit').",
    )
    label: constr(min_length=1) = Field(
        ..., description="中文 button label shown in UI."
    )
    required_persona: List[constr(min_length=1)] = Field(
        default_factory=list,
        description="RBAC personas allowed to trigger this action. Empty = no role gate.",
    )
    risk_tier: Literal["low", "medium", "high"] = Field(
        ...,
        description="Risk tier · drives PermissionRequest UI form-factor when triggered.",
    )
    description: Optional[constr(min_length=1)] = Field(
        None,
        description="Optional · tooltip / aria-label description.",
    )


class TokenBudgetState(_LiuyeBaseModel):
    """Per-turn token usage snapshot (v3 §2.5).

    Emitted alongside ``tool.completed`` or ``turn.completed`` so frontend
    can show a "token used / budget" indicator. ``model`` carries the
    provider+model pair the LLM caller actually routed to (PIPL audit
    trail · root §3.6).
    """

    used: conint(ge=0) = Field(
        ...,
        description="Cumulative tokens used in this turn so far (prompt + completion).",
    )
    limit: conint(ge=1) = Field(
        ...,
        description="Turn-level token budget · per-agent default · overrideable.",
    )
    model: constr(min_length=1) = Field(
        ...,
        description="Provider:model pair (e.g. 'deepseek:deepseek-chat' / 'dashscope:qwen-max'). PIPL audit · root §3.6.",
    )


__all__ = [
    # Re-exports from contract worker SSOT
    "Artifact",
    "ArtifactPatch",
    "EvidenceRef",
    "KBDoc",
    "LiuyeChatEvent",
    "PermissionRequestEventPayload",
    "ProgressMessage",
    "ToolCall",
    "TurnErrorPayload",
    # BFF cross-cutting protocols (v3 §2.5)
    "ArtifactAction",
    "LedgerReviewEvent",
    "PermissionRequest",
    "TokenBudgetState",
    "ValidationIssue",
]
