"""Tests for orchestrator/recovery.py — pure render_bat() string assertions."""
from __future__ import annotations

import sys
from pathlib import Path

# Inject scripts/ so `from orchestrator.recovery import ...` resolves.
_HERE = Path(__file__).resolve()
sys.path.insert(0, str(_HERE.parent.parent.parent))

from orchestrator.lib.mesh import Worktree  # noqa: E402
from orchestrator.recovery import (  # noqa: E402
    DEFAULT_ENV_LINES,
    VALID_PLATFORMS,
    _bash_env_chain,
    _bash_export,
    _load_env_lines,
    _read_stuck_names,
    _synthesize_env_lines,
    build_env_lines,
    detect_platform,
    render_applescript,
    render_bat,
    render_for_platform,
    render_shell_script,
)

# Representative explicit env set used by legacy-style tests below; matches
# what an operator who sets up scripts/claude-env.bat by hand would produce.
_FIXTURE_ENV = [
    'set "https_proxy=http://127.0.0.1:7897"',
    'set "http_proxy=http://127.0.0.1:7897"',
    'set "ALL_PROXY=http://127.0.0.1:7897"',
    'set "CLAUDE_CODE_GIT_BASH_PATH=D:\\Git\\usr\\bin\\bash.exe"',
]


def _sample_worktree() -> Worktree:
    return Worktree(
        name="agent6",
        path=Path("D:/claude code/demo-agent6"),
        branch="feat/agent6-v16",
        role="worker",
        description="report bot",
    )


def test_render_bat_contains_wt_invocation():
    bat = render_bat(_sample_worktree(), _FIXTURE_ENV)
    assert "wt -w 0 new-tab" in bat, (
        "missing wt new-tab launcher line:\n" + bat
    )


def test_render_bat_uses_backslash_path_and_title():
    bat = render_bat(_sample_worktree(), _FIXTURE_ENV)
    expected_path = "D:\\claude code\\demo-agent6"
    assert expected_path in bat, (
        f"expected backslash path {expected_path!r} in bat, got:\n{bat}"
    )
    assert '--title "claude-agent6"' in bat, (
        "title should be claude-<name>, got:\n" + bat
    )
    assert f'-d "{expected_path}"' in bat, (
        f"-d should point at the worktree path, got:\n{bat}"
    )


def test_render_bat_inlines_provided_env_lines():
    bat = render_bat(_sample_worktree(), _FIXTURE_ENV)
    for needle in _FIXTURE_ENV:
        assert needle in bat, f"missing env line {needle!r} in bat:\n{bat}"
    # All four must be chained inside the cmd /k argument so they run in
    # the spawned shell, not the launcher shell.
    assert "cmd /k" in bat, "expected cmd /k chain, got:\n" + bat
    assert " && claude" in bat, "claude must terminate the && chain, got:\n" + bat


def test_render_bat_with_no_env_lines_still_launches_claude():
    """Portable default: empty env list yields a clean `cmd /k claude` invocation."""
    bat = render_bat(_sample_worktree(), [])
    assert "cmd /k" in bat
    assert '"claude"' in bat, f"claude should be the sole cmd payload, got:\n{bat}"


def test_render_bat_header_carries_metadata():
    bat = render_bat(_sample_worktree(), _FIXTURE_ENV)
    assert bat.startswith("@echo off\n"), "bat must start with @echo off"
    assert "Auto-generated by orchestrator/recovery.py" in bat
    assert "Restart worker session for: agent6 (worker)" in bat
    assert "Branch: feat/agent6-v16" in bat


def test_default_env_lines_is_empty_alias():
    """R2 · hard-coded proxy fallback removed; DEFAULT_ENV_LINES kept as alias."""
    assert DEFAULT_ENV_LINES == []


def test_build_env_lines_prefers_claude_env_bat(tmp_path):
    helper = tmp_path / "claude-env.bat"
    helper.write_text(
        'set "https_proxy=http://proj.local:8888"\n'
        'set "ALL_PROXY=http://proj.local:8888"\n',
        encoding="utf-8",
    )
    # env vars would lose to the project file:
    lines = build_env_lines(
        claude_env_bat=helper,
        environ={"MESH_PROXY": "http://env.example:7897"},
    )
    assert lines == [
        'set "https_proxy=http://proj.local:8888"',
        'set "ALL_PROXY=http://proj.local:8888"',
    ]


def test_build_env_lines_falls_back_to_env_vars(tmp_path):
    missing = tmp_path / "nope.bat"
    lines = build_env_lines(
        claude_env_bat=missing,
        environ={
            "MESH_PROXY": "http://env.example:7897",
            "CLAUDE_CODE_GIT_BASH_PATH": "C:\\Git\\usr\\bin\\bash.exe",
        },
    )
    assert 'set "https_proxy=http://env.example:7897"' in lines
    assert 'set "ALL_PROXY=http://env.example:7897"' in lines
    assert 'set "CLAUDE_CODE_GIT_BASH_PATH=C:\\Git\\usr\\bin\\bash.exe"' in lines


def test_build_env_lines_empty_when_nothing_configured(tmp_path):
    missing = tmp_path / "nope.bat"
    lines = build_env_lines(claude_env_bat=missing, environ={})
    assert lines == []


def test_synthesize_env_lines_honours_mesh_proxy_priority():
    env = {
        "MESH_PROXY": "http://a:1",
        "http_proxy": "http://b:2",
        "HTTPS_PROXY": "http://c:3",
    }
    lines = _synthesize_env_lines(env)
    # MESH_PROXY wins over both http_proxy and HTTPS_PROXY.
    assert 'set "https_proxy=http://a:1"' in lines
    assert not any("http://b:2" in line for line in lines)
    assert not any("http://c:3" in line for line in lines)


def test_synthesize_env_lines_falls_through_to_http_proxy():
    lines = _synthesize_env_lines({"http_proxy": "http://standard:3128"})
    assert any("http://standard:3128" in line for line in lines)


def test_load_env_lines_backward_compat_returns_file_content(tmp_path):
    helper = tmp_path / "claude-env.bat"
    helper.write_text(
        'set "https_proxy=http://127.0.0.1:7897"\n'
        'set "ALL_PROXY=http://127.0.0.1:7897"\n',
        encoding="utf-8",
    )
    lines = _load_env_lines(helper)
    assert lines == [
        'set "https_proxy=http://127.0.0.1:7897"',
        'set "ALL_PROXY=http://127.0.0.1:7897"',
    ]


# ---------- R1 · cross-platform ----------

def test_bash_export_converts_quoted_set_line():
    assert _bash_export('set "https_proxy=http://proxy:8888"') == \
        "export https_proxy='http://proxy:8888'"


def test_bash_export_converts_bare_set_line():
    assert _bash_export("set HTTPS_PROXY=http://x") == "export HTTPS_PROXY='http://x'"


def test_bash_export_skips_unparseable():
    assert _bash_export("unrelated line").startswith("# (skipped")


def test_bash_env_chain_joins_with_double_amp():
    chain = _bash_env_chain(_FIXTURE_ENV)
    # Every valid export must be present; separator is && ; commented skips dropped.
    assert " && " in chain
    assert "export https_proxy='http://127.0.0.1:7897'" in chain
    assert "export CLAUDE_CODE_GIT_BASH_PATH='D:\\Git\\usr\\bin\\bash.exe'" in chain


def test_render_applescript_wraps_terminal_invocation():
    script = render_applescript(_sample_worktree(), _FIXTURE_ENV)
    assert script.startswith("-- Auto-generated"), script
    assert 'tell application "Terminal"' in script
    assert "activate" in script
    assert "do script" in script
    assert "exec claude" in script
    # Path should be POSIX-style inside the do-script cd.
    assert "cd 'D:/claude code/demo-agent6'" in script


def test_render_applescript_escapes_embedded_quotes():
    script = render_applescript(_sample_worktree(), [])
    # We pass no env, so the do-script should be `cd '<path>' && exec claude`
    # and must not contain an unescaped double quote in the middle of the body
    # (only the outer pair wraps the string).
    body_section = script.split("do script ", 1)[1]
    # The first char is `"`, then content, then closing `"`. Count raw dquotes
    # inside — any inner ones must appear as \" (which we count via plain split).
    assert body_section.startswith('"'), body_section
    # No unescaped " inside (every " should be preceded by \)
    inner = body_section[1:]
    closing_idx = None
    i = 0
    while i < len(inner):
        ch = inner[i]
        if ch == "\\":
            i += 2
            continue
        if ch == '"':
            closing_idx = i
            break
        i += 1
    assert closing_idx is not None, "AppleScript do-script must be properly closed"


def test_render_shell_script_is_executable_bash():
    script = render_shell_script(_sample_worktree(), _FIXTURE_ENV)
    assert script.startswith("#!/usr/bin/env bash\n")
    assert "set -e" in script
    assert "cd 'D:/claude code/demo-agent6'" in script
    assert "export https_proxy='http://127.0.0.1:7897'" in script
    assert script.rstrip().endswith("exec claude")


def test_render_shell_script_with_empty_env_is_still_valid():
    script = render_shell_script(_sample_worktree(), [])
    assert "exec claude" in script
    # No stray export lines when env list is empty:
    assert "export " not in script


def test_render_for_platform_dispatches_by_target():
    body_win, ext_win = render_for_platform(_sample_worktree(), _FIXTURE_ENV, "windows")
    assert ext_win == ".bat"
    assert "wt -w 0 new-tab" in body_win

    body_mac, ext_mac = render_for_platform(_sample_worktree(), _FIXTURE_ENV, "macos")
    assert ext_mac == ".applescript"
    assert 'tell application "Terminal"' in body_mac

    body_lin, ext_lin = render_for_platform(_sample_worktree(), _FIXTURE_ENV, "linux")
    assert ext_lin == ".sh"
    assert body_lin.startswith("#!/usr/bin/env bash")


def test_render_for_platform_rejects_unknown():
    try:
        render_for_platform(_sample_worktree(), [], "solaris")
    except ValueError as e:
        assert "unknown platform" in str(e)
    else:
        raise AssertionError("expected ValueError for unknown platform")


def test_detect_platform_returns_valid_tag():
    tag = detect_platform()
    assert tag in VALID_PLATFORMS


def test_read_stuck_names_workers_shape(tmp_path):
    state = tmp_path / "state.json"
    state.write_text(
        '{"workers": {"agent1": {"status": "stuck:idle-90s"}, '
        '"agent2": {"status": "ok"}}}',
        encoding="utf-8",
    )
    assert _read_stuck_names(state) == ["agent1"]


def test_read_stuck_names_flat_string_shape(tmp_path):
    state = tmp_path / "state.json"
    state.write_text(
        '{"agent3": "stuck:no-heartbeat", "agent4": "ok"}',
        encoding="utf-8",
    )
    assert _read_stuck_names(state) == ["agent3"]


def test_read_stuck_names_missing_file(tmp_path):
    assert _read_stuck_names(tmp_path / "absent.json") == []


if __name__ == "__main__":
    import tempfile

    tests = [
        test_render_bat_contains_wt_invocation,
        test_render_bat_uses_backslash_path_and_title,
        test_render_bat_inlines_provided_env_lines,
        test_render_bat_with_no_env_lines_still_launches_claude,
        test_render_bat_header_carries_metadata,
        test_default_env_lines_is_empty_alias,
        test_build_env_lines_prefers_claude_env_bat,
        test_build_env_lines_falls_back_to_env_vars,
        test_build_env_lines_empty_when_nothing_configured,
        test_synthesize_env_lines_honours_mesh_proxy_priority,
        test_synthesize_env_lines_falls_through_to_http_proxy,
        test_load_env_lines_backward_compat_returns_file_content,
        test_bash_export_converts_quoted_set_line,
        test_bash_export_converts_bare_set_line,
        test_bash_export_skips_unparseable,
        test_bash_env_chain_joins_with_double_amp,
        test_render_applescript_wraps_terminal_invocation,
        test_render_applescript_escapes_embedded_quotes,
        test_render_shell_script_is_executable_bash,
        test_render_shell_script_with_empty_env_is_still_valid,
        test_render_for_platform_dispatches_by_target,
        test_render_for_platform_rejects_unknown,
        test_detect_platform_returns_valid_tag,
        test_read_stuck_names_workers_shape,
        test_read_stuck_names_flat_string_shape,
        test_read_stuck_names_missing_file,
    ]
    failed = 0
    for t in tests:
        try:
            sig = t.__code__.co_varnames[: t.__code__.co_argcount]
            if "tmp_path" in sig:
                with tempfile.TemporaryDirectory() as d:
                    t(Path(d))
            else:
                t()
            print(f"[OK] {t.__name__}")
        except AssertionError as e:
            failed += 1
            print(f"[FAIL] {t.__name__}: {e}")
    if failed:
        print(f"\n[FAIL] {failed}/{len(tests)} recovery tests failed")
        sys.exit(1)
    print(f"\n[ALL PASS] {len(tests)} recovery tests")
