"""Tests for orchestrator/recovery.py — pure render_bat() string assertions."""
from __future__ import annotations

import sys
from pathlib import Path

# Inject scripts/ so `from orchestrator.recovery import ...` resolves.
_HERE = Path(__file__).resolve()
sys.path.insert(0, str(_HERE.parent.parent.parent))

from orchestrator.lib.mesh import Worktree  # noqa: E402
from orchestrator.recovery import (  # noqa: E402
    DEFAULT_ENV_LINES,
    _load_env_lines,
    _read_stuck_names,
    render_bat,
)


def _sample_worktree() -> Worktree:
    return Worktree(
        name="agent6",
        path=Path("D:/claude code/demo-agent6"),
        branch="feat/agent6-v16",
        role="worker",
        description="report bot",
    )


def test_render_bat_contains_wt_invocation():
    bat = render_bat(_sample_worktree(), DEFAULT_ENV_LINES)
    assert "wt -w 0 new-tab" in bat, (
        "missing wt new-tab launcher line:\n" + bat
    )


def test_render_bat_uses_backslash_path_and_title():
    bat = render_bat(_sample_worktree(), DEFAULT_ENV_LINES)
    expected_path = "D:\\claude code\\demo-agent6"
    assert expected_path in bat, (
        f"expected backslash path {expected_path!r} in bat, got:\n{bat}"
    )
    assert '--title "claude-agent6"' in bat, (
        "title should be claude-<name>, got:\n" + bat
    )
    assert f'-d "{expected_path}"' in bat, (
        f"-d should point at the worktree path, got:\n{bat}"
    )


def test_render_bat_inlines_all_four_env_sets():
    bat = render_bat(_sample_worktree(), DEFAULT_ENV_LINES)
    for needle in (
        'set "https_proxy=http://127.0.0.1:7897"',
        'set "http_proxy=http://127.0.0.1:7897"',
        'set "ALL_PROXY=http://127.0.0.1:7897"',
        'set "CLAUDE_CODE_GIT_BASH_PATH=D:\\Git\\usr\\bin\\bash.exe"',
    ):
        assert needle in bat, f"missing env line {needle!r} in bat:\n{bat}"
    # All four must be chained inside the cmd /k argument so they run in
    # the spawned shell, not the launcher shell.
    assert "cmd /k" in bat, "expected cmd /k chain, got:\n" + bat
    assert " && claude" in bat, "claude must terminate the && chain, got:\n" + bat


def test_render_bat_header_carries_metadata():
    bat = render_bat(_sample_worktree(), DEFAULT_ENV_LINES)
    assert bat.startswith("@echo off\n"), "bat must start with @echo off"
    assert "Auto-generated by orchestrator/recovery.py" in bat
    assert "Restart worker session for: agent6 (worker)" in bat
    assert "Branch: feat/agent6-v16" in bat


def test_load_env_lines_falls_back_when_missing(tmp_path):
    missing = tmp_path / "nope.bat"
    lines = _load_env_lines(missing)
    assert lines == DEFAULT_ENV_LINES, (
        "missing claude-env.bat must fall back to DEFAULT_ENV_LINES"
    )


def test_load_env_lines_parses_real_helper(tmp_path):
    helper = tmp_path / "claude-env.bat"
    helper.write_text(
        "@echo off\n"
        "REM comment\n"
        'set "https_proxy=http://127.0.0.1:7897"\n'
        'set "ALL_PROXY=http://127.0.0.1:7897"\n'
        "claude\n",
        encoding="utf-8",
    )
    lines = _load_env_lines(helper)
    assert lines == [
        'set "https_proxy=http://127.0.0.1:7897"',
        'set "ALL_PROXY=http://127.0.0.1:7897"',
    ]


def test_read_stuck_names_workers_shape(tmp_path):
    state = tmp_path / "state.json"
    state.write_text(
        '{"workers": {"agent1": {"status": "stuck:idle-90s"}, '
        '"agent2": {"status": "ok"}}}',
        encoding="utf-8",
    )
    assert _read_stuck_names(state) == ["agent1"]


def test_read_stuck_names_flat_string_shape(tmp_path):
    state = tmp_path / "state.json"
    state.write_text(
        '{"agent3": "stuck:no-heartbeat", "agent4": "ok"}',
        encoding="utf-8",
    )
    assert _read_stuck_names(state) == ["agent3"]


def test_read_stuck_names_missing_file(tmp_path):
    assert _read_stuck_names(tmp_path / "absent.json") == []


if __name__ == "__main__":
    import tempfile

    tests = [
        test_render_bat_contains_wt_invocation,
        test_render_bat_uses_backslash_path_and_title,
        test_render_bat_inlines_all_four_env_sets,
        test_render_bat_header_carries_metadata,
        test_load_env_lines_falls_back_when_missing,
        test_load_env_lines_parses_real_helper,
        test_read_stuck_names_workers_shape,
        test_read_stuck_names_flat_string_shape,
        test_read_stuck_names_missing_file,
    ]
    failed = 0
    for t in tests:
        try:
            sig = t.__code__.co_varnames[: t.__code__.co_argcount]
            if "tmp_path" in sig:
                with tempfile.TemporaryDirectory() as d:
                    t(Path(d))
            else:
                t()
            print(f"[OK] {t.__name__}")
        except AssertionError as e:
            failed += 1
            print(f"[FAIL] {t.__name__}: {e}")
    if failed:
        print(f"\n[FAIL] {failed}/{len(tests)} recovery tests failed")
        sys.exit(1)
    print(f"\n[ALL PASS] {len(tests)} recovery tests")
