# AUTO-GENERATED · DO NOT EDIT BY HAND
# source: shared/contracts/liuye/schemas/*.json
# tool:   datamodel-code-generator (Pydantic v2)
# regen:  npm run contracts:sync  (from credit_matrix_next/)
#
# Field names use snake_case (matches Pydantic style) · populate_by_name=True
# means consumers can pass either snake_case or the JSON Schema property name.
# contract-locked per contracts.lock.json:codegen_options.py_alias_generator.
from __future__ import annotations

# ---- source: shared/contracts/liuye/schemas/artifact.schema.json ----
# generated by datamodel-codegen:
#   filename:  artifact.schema.json

from enum import Enum
from typing import Any, List, Literal, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Type(Enum):
    """
    5-enum lock (v3 §2.2 + brief §4.2 hardline). Adding a sixth value requires PM ratify + RFC.
    """

    credit_decision = 'credit_decision'
    report_draft = 'report_draft'
    channel_search = 'channel_search'
    ledger_decision = 'ledger_decision'
    kb_upload_result = 'kb_upload_result'


class Status(Enum):
    """
    Lifecycle status. streaming = patches still arriving · partial = some chunks missing · resolved = final snapshot ready · failed = aborted.
    """

    streaming = 'streaming'
    partial = 'partial'
    resolved = 'resolved'
    failed = 'failed'


class OwnerAgent(Enum):
    """
    Which Cowork agent owns this artifact's snapshot schema (Managed agents alert/compliance/riskctrl do not emit Artifacts directly · they write to decision_ledger instead per §3.1.1).
    """

    channel = 'channel'
    credit = 'credit'
    report = 'report'


class Verdict(Enum):
    """
    Optional QC verdict (e.g. quality_scorer 9-dim gate result). PARTIAL = some dimensions failed but artifact still usable.
    """

    pass_ = 'PASS'
    partial = 'PARTIAL'
    fail = 'FAIL'


class QcScore(BaseModel):
    """
    QC pass/total counter · presented alongside verdict.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    passed: conint(ge=0) = Field(..., description='Number of QC dimensions passed.')
    total: conint(ge=1) = Field(
        ...,
        description='Total QC dimensions evaluated (typically 9 per §8 quality_scorer).',
    )


class Op(Enum):
    """
    Patch operation type. replace = overwrite at path · append = push to array at path · merge = deep-merge object at path.
    """

    replace = 'replace'
    append = 'append'
    merge = 'merge'


class ChunkAssembly(Enum):
    """
    P1-10 R10 chunked patch · streaming = partial render allowed · final = merge into complete snapshot. Single chunk size ≤ 64KB per v3 §2.2 hardline.
    """

    streaming = 'streaming'
    final = 'final'


class ArtifactPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1) = Field(
        ..., description="Patch identifier · unique within an artifact's patches[]."
    )
    artifact_id: constr(min_length=1) = Field(
        ..., description='Parent Artifact.id this patch belongs to.'
    )
    base_version: conint(ge=0) = Field(
        ...,
        description='Artifact.version this patch is applied against · client rejects patch if Artifact.version != base_version (version mismatch → full snapshot pull · v3 §2.2 hardline).',
    )
    next_version: conint(ge=1) = Field(
        ...,
        description='Artifact.version after this patch applies · must equal base_version + 1.',
    )
    op: Op = Field(
        ...,
        description='Patch operation type. replace = overwrite at path · append = push to array at path · merge = deep-merge object at path.',
    )
    path: constr(min_length=1) = Field(
        ...,
        description="JSON Pointer (RFC 6901) into Artifact.snapshot · e.g. '/sections/0/body' or '/candidates'.",
    )
    value: Any = Field(
        ...,
        description='Value to apply at path · type depends on op (replace=any · append=item · merge=object). Open schema · per-type narrowing at consumer side.',
    )
    ts: AwareDatetime = Field(..., description='ISO 8601 UTC patch emit timestamp.')
    chunk_index: Optional[conint(ge=0)] = Field(
        None,
        description='P1-10 R10 chunked patch · chunk index starts at 0 and increments monotonically. Missing chunk_index/chunk_total = non-chunked patch (legacy compat).',
    )
    chunk_total: Optional[conint(ge=1)] = Field(
        None,
        description='P1-10 R10 chunked patch · total chunk count. Missing chunk_total = non-chunked patch. Client triggers full snapshot pull on chunk gap / version mismatch / chunk_total inconsistency.',
    )
    chunk_assembly: Optional[ChunkAssembly] = Field(
        None,
        description='P1-10 R10 chunked patch · streaming = partial render allowed · final = merge into complete snapshot. Single chunk size ≤ 64KB per v3 §2.2 hardline.',
    )


class Artifact(BaseModel):
    """
    Liuye 5-protocol member · Artifact + ArtifactPatch (v3 spec §2.2). ordered JSON Patch with monotonic version · NOT default-CRDT · supports chunked patches (P1-10 R10).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1) = Field(
        ..., description='Stable artifact identifier · stable across versions.'
    )
    schema_version: Literal['1'] = Field(
        ...,
        description="Liuye contract schema version · fixed '1' for the current spec lock.",
    )
    type: Type = Field(
        ...,
        description='5-enum lock (v3 §2.2 + brief §4.2 hardline). Adding a sixth value requires PM ratify + RFC.',
    )
    status: Status = Field(
        ...,
        description='Lifecycle status. streaming = patches still arriving · partial = some chunks missing · resolved = final snapshot ready · failed = aborted.',
    )
    source_tool_call_id: constr(min_length=1) = Field(
        ...,
        description='The ToolCall.id that produced this Artifact (root cause · Cowork→Managed handoff still references the original cowork tool_call_id via parent_tool_call_id chain).',
    )
    owner_agent: OwnerAgent = Field(
        ...,
        description="Which Cowork agent owns this artifact's snapshot schema (Managed agents alert/compliance/riskctrl do not emit Artifacts directly · they write to decision_ledger instead per §3.1.1).",
    )
    title: constr(min_length=1) = Field(
        ..., description='Human-readable title shown in artifact panel header.'
    )
    version: conint(ge=0) = Field(
        ...,
        description='Monotonic integer · increments by 1 per applied patch. version=0 = initial empty artifact.',
    )
    patches: List[ArtifactPatch] = Field(
        ...,
        description='Ordered JSON Patch history · most recent at end. Replay-able to reconstruct snapshot from base.',
    )
    snapshot: Any = Field(
        ...,
        description='Current materialized snapshot · validated against per-type outputSchema (e.g. CreditDecisionV1 / ReportDraftV1 / ChannelSearchV1). Schema is open here · type-specific narrowing happens at consumer side via inputSchemas.ts.',
    )
    verdict: Optional[Verdict] = Field(
        None,
        description='Optional QC verdict (e.g. quality_scorer 9-dim gate result). PARTIAL = some dimensions failed but artifact still usable.',
    )
    qc_score: Optional[QcScore] = Field(
        None, description='QC pass/total counter · presented alongside verdict.'
    )
    evidence_refs: List[constr(min_length=1)] = Field(
        ...,
        description="EvidenceRef.id list · all evidence backing this artifact's snapshot. evidence_refs MAY be empty during streaming but MUST be populated by resolved.",
    )
    created_at: AwareDatetime = Field(
        ...,
        description='ISO 8601 UTC · matches Python datetime.isoformat() and JS toISOString().',
    )
    updated_at: AwareDatetime = Field(
        ..., description='ISO 8601 UTC · updated on every patch application.'
    )
    resolved_at: Optional[AwareDatetime] = Field(
        None,
        description='ISO 8601 UTC · set when status transitions to resolved or failed.',
    )

# ---- source: shared/contracts/liuye/schemas/evidence_ref.schema.json ----
# generated by datamodel-codegen:
#   filename:  evidence_ref.schema.json

from enum import Enum
from typing import List, Literal, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Span(BaseModel):
    """
    Character span within parent KBDoc · used for re-highlighting in source viewer.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    start: conint(ge=0) = Field(
        ...,
        description='Excerpt start offset (character index) within the parent KBDoc content.',
    )
    end: conint(ge=0) = Field(
        ...,
        description='Excerpt end offset (character index) within the parent KBDoc content. end > start.',
    )


class Freshness(Enum):
    """
    Freshness 3-state (v3 §2.4 line 242 verbatim). fresh = within SLA per claim_type (root §3.5.1 FRESHNESS_SLA_DAYS · e.g. news 180d) · critical = near SLA boundary (warn but usable) · expired = past SLA (block as core_claim per recommendation_schema.staleness_policy_passed=false · background only). NOTE: this is contract-layer 3-enum · NOT the 5-band UI classification from shared/evidence_freshness.classify_freshness() (fresh/recent/aging/stale/very_stale) · adapter at consumer side.
    """

    fresh = 'fresh'
    critical = 'critical'
    expired = 'expired'


class DataTier(Enum):
    """
    Data tier 1-4 (v3 §2.4 line 243 verbatim · same as KBDoc.tier). Cached here for fast filter without joining KBDoc. Must equal parent kb_doc.tier · consumer verifies at sanity check.
    """

    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4


class SourceTier(Enum):
    """
    Optional · matches shared/data_tiers.DataTier str enum verbatim. When set must be consistent with data_tier int (1↔internal_authoritative · 2↔government · 3↔industry · 4↔public_web · unknown defaults to tier 4 handling).
    """

    internal_authoritative = 'internal_authoritative'
    government = 'government'
    industry = 'industry'
    public_web = 'public_web'
    unknown = 'unknown'


class EvidenceRef(BaseModel):
    """
    Liuye 5-protocol member · EvidenceRef (v3 spec §2.4 line 237-247). Evidence chain reference · points to a KBDoc.id + excerpt span. freshness 3-state (fresh/critical/expired) is the v3 contract enum · DIFFERENT from shared/evidence_freshness.classify_freshness() 5-band UI labels (fresh/recent/aging/stale/very_stale) · mapping done at consumer adapter (fresh→fresh · recent→fresh · aging→critical · stale→critical · very_stale→expired). decision_id added per P0-8 R9 · only set when EvidenceRef directly supports a cross-decision link (LE-05 sign-off lookup) · NOT for in-artifact backing (use Artifact.evidence_refs[] for that).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1) = Field(
        ...,
        description='Stable EvidenceRef identifier · referenced by Artifact.evidence_refs[] and message citations.',
    )
    schema_version: Literal['1'] = Field(
        ...,
        description="Liuye contract schema version · fixed '1' for the current spec lock.",
    )
    kb_doc_id: constr(min_length=1) = Field(
        ...,
        description='Parent KBDoc.id this evidence excerpt comes from. Resolves to a kb_doc.schema.json instance.',
    )
    excerpt: constr(min_length=1) = Field(
        ...,
        description='Quoted excerpt text (v3 §2.4 line 240 verbatim · per appendix C: length cap and PII redaction policy applied). Shown in evidence drawer panel.',
    )
    span: Span = Field(
        ...,
        description='Character span within parent KBDoc · used for re-highlighting in source viewer.',
    )
    freshness: Freshness = Field(
        ...,
        description='Freshness 3-state (v3 §2.4 line 242 verbatim). fresh = within SLA per claim_type (root §3.5.1 FRESHNESS_SLA_DAYS · e.g. news 180d) · critical = near SLA boundary (warn but usable) · expired = past SLA (block as core_claim per recommendation_schema.staleness_policy_passed=false · background only). NOTE: this is contract-layer 3-enum · NOT the 5-band UI classification from shared/evidence_freshness.classify_freshness() (fresh/recent/aging/stale/very_stale) · adapter at consumer side.',
    )
    data_tier: DataTier = Field(
        ...,
        description='Data tier 1-4 (v3 §2.4 line 243 verbatim · same as KBDoc.tier). Cached here for fast filter without joining KBDoc. Must equal parent kb_doc.tier · consumer verifies at sanity check.',
    )
    related_artifact_ids: List[constr(min_length=1)] = Field(
        ...,
        description='Artifact.id list · all artifacts whose snapshot is backed by this evidence (v3 §2.4 line 244).',
    )
    cite_in_message_ids: List[constr(min_length=1)] = Field(
        ...,
        description='Message.id list · chat messages that inline-cite this evidence (v3 §2.4 line 245). Footnote-style citation map in conversation view.',
    )
    decision_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · P0-8 R9. Cross-decision link · set ONLY when this evidence directly supports a decision_ledger entry (LE-05 sign-off lookup target). For normal in-artifact backing use related_artifact_ids[] instead · NOT decision_id. Mapping case matrix to be ratified separately.',
    )
    evidence_date: Optional[AwareDatetime] = Field(
        None,
        description='ISO 8601 UTC · event occurrence date for this evidence (NOT fetched_at · NOT collected_at). Per root §3.5.1 第 6 原则 hardline: evidence missing evidence_date cannot serve as core claim. Maps to recommendation_schema.evidence_date semantics.',
    )
    retrieved_at: Optional[AwareDatetime] = Field(
        None,
        description='ISO 8601 UTC · when we retrieved this evidence excerpt. Distinct from KBDoc.collected_at (whole-doc fetch) · this is excerpt-level retrieval timestamp.',
    )
    source_url: Optional[str] = Field(
        None,
        description='Optional · source URL (e.g. https://www.cbirc.gov.cn/...) or internal source identifier (internal://crm/holdings). Mirrors recommendation_schema.source_url semantics. URI-reference allows both http(s) and internal:// pseudo-scheme.',
    )
    source_tier: Optional[SourceTier] = Field(
        None,
        description='Optional · matches shared/data_tiers.DataTier str enum verbatim. When set must be consistent with data_tier int (1↔internal_authoritative · 2↔government · 3↔industry · 4↔public_web · unknown defaults to tier 4 handling).',
    )

# ---- source: shared/contracts/liuye/schemas/kb_doc.schema.json ----
# generated by datamodel-codegen:
#   filename:  kb_doc.schema.json

from enum import Enum
from typing import Literal, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Type(Enum):
    """
    KBDoc provenance type. upload = RM/审贷员 manual upload · pulled = SearchProvider auto-fetch (Tavily/akshare/gov_cn/...) · mock = fixture/demo data (反 5 原则 §3.5 boundary).
    """

    upload = 'upload'
    pulled = 'pulled'
    mock = 'mock'


class Tier(Enum):
    """
    Data tier 1-4 (v3 §2.4 line 228 verbatim · maps to root §3.5.1 DataTier enum). 1=internal_authoritative (bank internal · 100% trust) · 2=government (银保监/央行/税务/法院 · <30d freshness) · 3=industry (上市公告/评级/研报) · 4=public_web (新闻/Tavily · core-claim ban). NOTE: v3 uses int tier · shared/data_tiers.DataTier is a str enum (internal_authoritative/government/industry/public_web) · mapping done at consumer adapter (int 1↔internal_authoritative etc).
    """

    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4


class SourceType(Enum):
    """
    Source channel type (v3 §2.4 line 229 verbatim). gov = government portal · enterprise = enterprise registry (qichacha/tianyancha) · tavily = Tavily web search · internal = bank internal system (CRM/流水/征信) · user = RM/审贷员 uploaded doc.
    """

    gov = 'gov'
    enterprise = 'enterprise'
    tavily = 'tavily'
    internal = 'internal'
    user = 'user'


class VerificationMethod(Enum):
    """
    Verification level (v3 §2.4 line 232 verbatim). signature = digital signature verified (PDF/PKCS#7) · cross_check = multi-source corroborated · manual = human-verified · unverified = raw fetch with no verification (typical for tavily/web).
    """

    signature = 'signature'
    cross_check = 'cross_check'
    manual = 'manual'
    unverified = 'unverified'


class PiplRegion(Enum):
    """
    PIPL cross-border residency (v3 §2.4 line 234 verbatim · root §3.6 PIPL fallback chain). cn = mainland data residency · overseas = ex-mainland (US/SG/...). Required for audit log when LLM call routes overseas (moonshot/openai). Optional in KBDoc since most internal docs are cn by default · explicit overseas marker for compliance trace.
    """

    cn = 'cn'
    overseas = 'overseas'


class KBDoc(BaseModel):
    """
    Liuye 5-protocol member · KBDoc (v3 spec §2.4). Knowledge-base document metadata · referenced by EvidenceRef.kb_doc_id. tier 1-4 per root §3.5.1 data tier hierarchy (Tier 1 internal authoritative → Tier 4 public web · core-claim ban on Tier 4 alone). pipl_region tracks PIPL cross-border data residency · cn = mainland · overseas = ex-mainland (audit log required per root §3.6).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1) = Field(
        ...,
        description='Stable KBDoc identifier · referenced by EvidenceRef.kb_doc_id.',
    )
    schema_version: Literal['1'] = Field(
        ...,
        description="Liuye contract schema version · fixed '1' for the current spec lock.",
    )
    title: constr(min_length=1) = Field(
        ...,
        description='Human-readable document title shown in KB browser and evidence panel.',
    )
    type: Type = Field(
        ...,
        description='KBDoc provenance type. upload = RM/审贷员 manual upload · pulled = SearchProvider auto-fetch (Tavily/akshare/gov_cn/...) · mock = fixture/demo data (反 5 原则 §3.5 boundary).',
    )
    tier: Tier = Field(
        ...,
        description='Data tier 1-4 (v3 §2.4 line 228 verbatim · maps to root §3.5.1 DataTier enum). 1=internal_authoritative (bank internal · 100% trust) · 2=government (银保监/央行/税务/法院 · <30d freshness) · 3=industry (上市公告/评级/研报) · 4=public_web (新闻/Tavily · core-claim ban). NOTE: v3 uses int tier · shared/data_tiers.DataTier is a str enum (internal_authoritative/government/industry/public_web) · mapping done at consumer adapter (int 1↔internal_authoritative etc).',
    )
    source_type: SourceType = Field(
        ...,
        description='Source channel type (v3 §2.4 line 229 verbatim). gov = government portal · enterprise = enterprise registry (qichacha/tianyancha) · tavily = Tavily web search · internal = bank internal system (CRM/流水/征信) · user = RM/审贷员 uploaded doc.',
    )
    collected_at: AwareDatetime = Field(
        ...,
        description='ISO 8601 UTC · when we fetched/received this doc. Maps to recommendation_schema.retrieved_at semantics.',
    )
    valid_until: Optional[AwareDatetime] = Field(
        None,
        description='Optional · document validity expiry (e.g. signed PDF cert expiry · government notice retraction date).',
    )
    verification_method: VerificationMethod = Field(
        ...,
        description='Verification level (v3 §2.4 line 232 verbatim). signature = digital signature verified (PDF/PKCS#7) · cross_check = multi-source corroborated · manual = human-verified · unverified = raw fetch with no verification (typical for tavily/web).',
    )
    content_hash: constr(pattern=r'^[a-fA-F0-9]{64}$') = Field(
        ...,
        description='SHA-256 content hash · 64 lowercase hex chars (v3 §2.4 line 233 verbatim). Used for KB dedup and tamper detection. Recomputed on re-fetch · mismatch triggers freshness invalidation.',
    )
    pipl_region: Optional[PiplRegion] = Field(
        None,
        description='PIPL cross-border residency (v3 §2.4 line 234 verbatim · root §3.6 PIPL fallback chain). cn = mainland data residency · overseas = ex-mainland (US/SG/...). Required for audit log when LLM call routes overseas (moonshot/openai). Optional in KBDoc since most internal docs are cn by default · explicit overseas marker for compliance trace.',
    )

# ---- source: shared/contracts/liuye/schemas/liuye_chat_event.schema.json ----
# generated by datamodel-codegen:
#   filename:  liuye_chat_event.schema.json

from enum import Enum
from typing import Any, List, Literal, Optional, Union

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class Event(Enum):
    """
    11 SSE event types (v3 §2.1 verbatim · PM 2026-05-11 ratify permission.request as 11th · control-layer explicit). heartbeat = 15s tick · client treats dead after 30s silence.
    """

    turn_started = 'turn.started'
    message_created = 'message.created'
    tool_started = 'tool.started'
    tool_progress = 'tool.progress'
    tool_completed = 'tool.completed'
    artifact_patch = 'artifact.patch'
    evidence_attached = 'evidence.attached'
    turn_completed = 'turn.completed'
    turn_error = 'turn.error'
    permission_request = 'permission.request'
    heartbeat = 'heartbeat'


class Event2(Enum):
    """
    11 SSE event types (v3 §2.1 verbatim · PM 2026-05-11 ratify permission.request as 11th · control-layer explicit). heartbeat = 15s tick · client treats dead after 30s silence.
    """

    turn_started = 'turn.started'
    message_created = 'message.created'
    tool_started = 'tool.started'
    tool_progress = 'tool.progress'
    tool_completed = 'tool.completed'
    artifact_patch = 'artifact.patch'
    evidence_attached = 'evidence.attached'
    turn_completed = 'turn.completed'
    turn_error = 'turn.error'
    permission_request = 'permission.request'
    heartbeat = 'heartbeat'
    turn_started_1 = 'turn.started'
    message_created_1 = 'message.created'
    tool_started_1 = 'tool.started'
    tool_progress_1 = 'tool.progress'
    tool_completed_1 = 'tool.completed'
    artifact_patch_1 = 'artifact.patch'
    evidence_attached_1 = 'evidence.attached'
    turn_completed_1 = 'turn.completed'
    heartbeat_1 = 'heartbeat'


class LiuyeChatEvent3(BaseModel):
    """
    All other 9 event types · payload narrowing left for follow-up schema iteration (artifact.patch payload = ArtifactPatch · evidence.attached payload = EvidenceRef · tool.progress payload = ProgressMessage). Schema kept open here to avoid premature lock before W1 D2+ fixture work.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: Literal['1'] = Field(
        ...,
        description="Liuye contract schema version · fixed '1' for the current spec lock.",
    )
    event: Event2 = Field(
        ...,
        description='11 SSE event types (v3 §2.1 verbatim · PM 2026-05-11 ratify permission.request as 11th · control-layer explicit). heartbeat = 15s tick · client treats dead after 30s silence.',
    )
    turn_id: constr(min_length=1) = Field(
        ...,
        description='Conversation turn identifier · same across all events within one user turn. Managed handoff = new turn_id with parent_turn_id link (P0-8 R9).',
    )
    message_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on message.created / turn.completed where a chat message is associated.',
    )
    tool_call_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on tool.* / artifact.patch / evidence.attached / permission.request events when bound to a ToolCall.',
    )
    artifact_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on artifact.patch / evidence.attached / tool.completed events when bound to an Artifact.',
    )
    trace_id: constr(min_length=1) = Field(
        ...,
        description='Distributed trace identifier · spans across BFF + 6 backend agents + LLM caller audit log. Required on every event for cross-system correlation.',
    )
    seq: conint(ge=0) = Field(
        ...,
        description='Monotonic sequence number within a turn_id · client uses for gap detection (seq gap < 10 + disconnect < 30s → Last-Event-ID resume · else full snapshot pull). v3 §2.1 SSE hardline.',
    )
    ts: AwareDatetime = Field(
        ...,
        description='ISO 8601 UTC event emit timestamp · matches Python datetime.isoformat() and JS toISOString().',
    )
    payload: Any = Field(
        ...,
        description='Event-specific payload. oneOf narrowing per event below · open for event types whose payload schema is still under iteration (P0/P1 followup). Critical payloads (TurnErrorPayload + PermissionRequestEventPayload) are fully specified in $defs.',
    )


class TurnErrorPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: constr(min_length=1) = Field(
        ...,
        description="Machine-readable error code (e.g. 'LLM_RATE_LIMIT' · 'TOOL_TIMEOUT' · 'PIPL_BLOCKED'). Stable across versions for telemetry grouping.",
    )
    message: constr(min_length=1) = Field(
        ...,
        description='Internal/log message · English · for ops + trace correlation. NOT shown to RM directly.',
    )
    retryable: bool = Field(
        ...,
        description='Whether the same turn can be safely retried (idempotent). false = user must change input or wait for ops fix.',
    )
    human_hint: constr(min_length=1) = Field(
        ...,
        description="中文 RM-facing hint (e.g. '系统繁忙 · 30 秒后自动重试'). What the customer-manager sees in error banner. PII redaction MUST be applied before write.",
    )
    trace_id: constr(min_length=1) = Field(
        ...,
        description='Echoed from envelope · enables RM to share trace_id with support for diagnosis.',
    )
    turn_id: constr(min_length=1) = Field(..., description='Echoed from envelope.')
    tool_call_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set when error originates from a specific ToolCall (not turn-level).',
    )
    seq: conint(ge=0) = Field(
        ..., description='Echoed from envelope · the seq at which error occurred.'
    )
    retry_after_ms: Optional[conint(ge=0)] = Field(
        None,
        description='Optional · suggested client retry delay in milliseconds (e.g. rate-limit backoff).',
    )
    fallback_available: Optional[bool] = Field(
        None,
        description='Optional · whether a degraded fallback path is available (e.g. PIPL block → use cn provider chain).',
    )


class RiskTier(Enum):
    """
    3-tier risk classification · drives UI form factor: low=inline confirm · medium=modal · high=drawer with reason input. PM 2026-05-11 ratify.
    """

    low = 'low'
    medium = 'medium'
    high = 'high'


class Scope(Enum):
    """
    Optional · grant scope. once = single action · session = current session · always = persistent until revoked. UI MUST default to 'once' for high-risk.
    """

    once = 'once'
    session = 'session'
    always = 'always'


class PermissionRequestEventPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: constr(min_length=1) = Field(
        ...,
        description='Same as PermissionRequest.id · stable identifier for this permission decision (idempotent across resends).',
    )
    risk_tier: RiskTier = Field(
        ...,
        description='3-tier risk classification · drives UI form factor: low=inline confirm · medium=modal · high=drawer with reason input. PM 2026-05-11 ratify.',
    )
    action: constr(min_length=1) = Field(
        ...,
        description="Action identifier (e.g. 'credit_decision_submit' / 'ledger_write' / 'pipl_overseas_call'). Backend canonical id · not display label.",
    )
    idempotency_key: constr(min_length=1) = Field(
        ...,
        description='Required on all irreversible actions · prevents double-execution if user double-clicks grant. Backend MUST dedupe on this key.',
    )
    required_persona: Optional[List[constr(min_length=1)]] = Field(
        None,
        description="Optional · RBAC required persona list (e.g. ['credit_officer', 'compliance_officer']). Backend-driven · frontend MUST NOT hardcode role names.",
    )
    disabled_reason: Optional[constr(min_length=1)] = Field(
        None,
        description="Optional · when current persona lacks required role · UI shows greyed-out button with explicit reason text. Example: '需要合规官签字 · 当前角色无权限'.",
    )
    reason_required: Optional[bool] = Field(
        None,
        description='Optional · high-risk drawer requires user to type a reason before grant button enables. Default false for low/medium · typically true for high.',
    )
    rule_source: Optional[constr(min_length=1)] = Field(
        None,
        description="Optional · audit trace · which policy emitted this request (e.g. 'policy.rbac' / 'policy.ledger_write' / 'policy.pipl'). Surfaces in decision_ledger for compliance review.",
    )
    scope: Optional[Scope] = Field(
        None,
        description="Optional · grant scope. once = single action · session = current session · always = persistent until revoked. UI MUST default to 'once' for high-risk.",
    )
    explanation: Optional[constr(min_length=1)] = Field(
        None,
        description="Optional · human-readable 中文 explanation shown in confirmation UI (e.g. '此操作将向决策账本写入授信决定 · 5 年留档 · 受银保监审计').",
    )
    consequences: Optional[List[constr(min_length=1)]] = Field(
        None,
        description="Optional · enumerated consequences (e.g. ['不可逆 · 写入 decision_ledger', '触发 PermissionRequest 全链路审计', '5 年留档']). UI bullet-list in high-risk drawer.",
    )


class LiuyeChatEvent1(BaseModel):
    """
    turn.error event · payload must conform to TurnErrorPayload (v3 §2.1 line 56-67 verbatim).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: Literal['1'] = Field(
        ...,
        description="Liuye contract schema version · fixed '1' for the current spec lock.",
    )
    event: Literal['turn.error'] = Field(
        ...,
        description='11 SSE event types (v3 §2.1 verbatim · PM 2026-05-11 ratify permission.request as 11th · control-layer explicit). heartbeat = 15s tick · client treats dead after 30s silence.',
    )
    turn_id: constr(min_length=1) = Field(
        ...,
        description='Conversation turn identifier · same across all events within one user turn. Managed handoff = new turn_id with parent_turn_id link (P0-8 R9).',
    )
    message_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on message.created / turn.completed where a chat message is associated.',
    )
    tool_call_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on tool.* / artifact.patch / evidence.attached / permission.request events when bound to a ToolCall.',
    )
    artifact_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on artifact.patch / evidence.attached / tool.completed events when bound to an Artifact.',
    )
    trace_id: constr(min_length=1) = Field(
        ...,
        description='Distributed trace identifier · spans across BFF + 6 backend agents + LLM caller audit log. Required on every event for cross-system correlation.',
    )
    seq: conint(ge=0) = Field(
        ...,
        description='Monotonic sequence number within a turn_id · client uses for gap detection (seq gap < 10 + disconnect < 30s → Last-Event-ID resume · else full snapshot pull). v3 §2.1 SSE hardline.',
    )
    ts: AwareDatetime = Field(
        ...,
        description='ISO 8601 UTC event emit timestamp · matches Python datetime.isoformat() and JS toISOString().',
    )
    payload: TurnErrorPayload = Field(
        ...,
        description='Event-specific payload. oneOf narrowing per event below · open for event types whose payload schema is still under iteration (P0/P1 followup). Critical payloads (TurnErrorPayload + PermissionRequestEventPayload) are fully specified in $defs.',
    )


class LiuyeChatEvent2(BaseModel):
    """
    permission.request event · payload must conform to PermissionRequestEventPayload (v3 §2.1 line 69-82 verbatim · PM 2026-05-11 ratify · control-layer explicit · NOT via SSE v1 adapter).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: Literal['1'] = Field(
        ...,
        description="Liuye contract schema version · fixed '1' for the current spec lock.",
    )
    event: Literal['permission.request'] = Field(
        ...,
        description='11 SSE event types (v3 §2.1 verbatim · PM 2026-05-11 ratify permission.request as 11th · control-layer explicit). heartbeat = 15s tick · client treats dead after 30s silence.',
    )
    turn_id: constr(min_length=1) = Field(
        ...,
        description='Conversation turn identifier · same across all events within one user turn. Managed handoff = new turn_id with parent_turn_id link (P0-8 R9).',
    )
    message_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on message.created / turn.completed where a chat message is associated.',
    )
    tool_call_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on tool.* / artifact.patch / evidence.attached / permission.request events when bound to a ToolCall.',
    )
    artifact_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · set on artifact.patch / evidence.attached / tool.completed events when bound to an Artifact.',
    )
    trace_id: constr(min_length=1) = Field(
        ...,
        description='Distributed trace identifier · spans across BFF + 6 backend agents + LLM caller audit log. Required on every event for cross-system correlation.',
    )
    seq: conint(ge=0) = Field(
        ...,
        description='Monotonic sequence number within a turn_id · client uses for gap detection (seq gap < 10 + disconnect < 30s → Last-Event-ID resume · else full snapshot pull). v3 §2.1 SSE hardline.',
    )
    ts: AwareDatetime = Field(
        ...,
        description='ISO 8601 UTC event emit timestamp · matches Python datetime.isoformat() and JS toISOString().',
    )
    payload: PermissionRequestEventPayload = Field(
        ...,
        description='Event-specific payload. oneOf narrowing per event below · open for event types whose payload schema is still under iteration (P0/P1 followup). Critical payloads (TurnErrorPayload + PermissionRequestEventPayload) are fully specified in $defs.',
    )


class LiuyeChatEvent(
    RootModel[Union[LiuyeChatEvent1, LiuyeChatEvent2, LiuyeChatEvent3]]
):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Union[LiuyeChatEvent1, LiuyeChatEvent2, LiuyeChatEvent3] = Field(
        ...,
        description='Liuye 5-protocol member · SSE envelope for Liuye BFF → frontend (v3 spec §2.1). 11 event types · permission.request added per PM 2026-05-11 ratify (control-layer explicit · NOT borrowed from tool.progress.payload). heartbeat 15s/30s · reconnect rules: seq gap < 10 and disconnect < 30s → Last-Event-ID resume · else full snapshot pull.',
        title='LiuyeChatEvent',
    )

# ---- source: shared/contracts/liuye/schemas/tool_call.schema.json ----
# generated by datamodel-codegen:
#   filename:  tool_call.schema.json

from enum import Enum
from typing import Any, List, Literal, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Agent(Enum):
    """
    6-agent enum (v3 §2.3 verbatim · root §4 SSOT). Cowork: channel/credit/report. Managed: alert/compliance/riskctrl.
    """

    channel = 'channel'
    credit = 'credit'
    report = 'report'
    riskctrl = 'riskctrl'
    alert = 'alert'
    compliance = 'compliance'


class Boundary(Enum):
    """
    Tool boundary type per root §3.1.1. cowork = real-time SSE (< 5s p95) · managed_readonly = batch (job_id + status + retry).
    """

    cowork = 'cowork'
    managed_readonly = 'managed_readonly'


class Status(Enum):
    """
    ToolStatus 8-enum lock (v3 §2.3 line 179-181 verbatim · brief §4.2 hardline). Lifecycle: queued → connecting → running → streaming → (completed|failed|aborted|idle_timeout). idle_timeout = no progress emitted within SLA window (per agent SLA · root §3.1.1).
    """

    queued = 'queued'
    connecting = 'connecting'
    running = 'running'
    streaming = 'streaming'
    idle_timeout = 'idle_timeout'
    completed = 'completed'
    failed = 'failed'
    aborted = 'aborted'


class Error(BaseModel):
    """
    Set when status = failed. Mirrors TurnErrorPayload shape (subset) per liuye_chat_event.schema.json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: constr(min_length=1) = Field(
        ...,
        description='Error code · machine-readable enum (e.g. TOOL_TIMEOUT, INPUT_VALIDATION, PROVIDER_UNAVAILABLE).',
    )
    message: constr(min_length=1) = Field(
        ...,
        description='Human-readable error message · displayed to operator (RM/审贷员/合规官).',
    )
    trace_id: constr(min_length=1) = Field(
        ..., description='Trace identifier · for audit_service correlation.'
    )


class Status1(Enum):
    """
    ProgressMessage status 5-enum (v3 §2.3 line 207 verbatim). DIFFERENT from ToolCall.status 8-enum · ProgressMessage status is stage-level lifecycle (warning = stage degraded but pipeline continues · error = stage fatal · upgrades ToolCall.status to failed at next emit).
    """

    pending = 'pending'
    running = 'running'
    done = 'done'
    warning = 'warning'
    error = 'error'


class ProgressMessage(BaseModel):
    """
    ProgressMessage (v3 §2.3 line 195-209). Tool-call lifecycle stage progress · emitted via tool.progress SSE event.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1) = Field(
        ...,
        description='ProgressMessage identifier · unique within tool_call.progress[].',
    )
    turn_id: constr(min_length=1) = Field(
        ..., description='Parent conversation turn identifier.'
    )
    tool_call_id: constr(min_length=1) = Field(
        ..., description='Parent ToolCall.id this progress belongs to.'
    )
    trace_id: constr(min_length=1) = Field(
        ..., description='Trace identifier · for audit_service correlation.'
    )
    seq: conint(ge=0) = Field(
        ...,
        description='Monotonic sequence · emitted in order from the same tool_call. Client uses seq to detect gaps and trigger reconnect (per liuye_chat_event.schema.json reconnect rules).',
    )
    ts: AwareDatetime = Field(
        ..., description='ISO 8601 UTC · progress emit timestamp.'
    )
    stage_key: constr(min_length=1) = Field(
        ...,
        description="Internal stage key · stable identifier (e.g. 'kb_scan', 'evidence_collect', 'llm_grounded_gen') · appears in tooltip/trace · NOT for end-user display.",
    )
    stage_label: constr(min_length=1) = Field(
        ...,
        description="Chinese-facing stage label (e.g. '知识库扫描', '证据汇集', 'LLM 接地生成') · displayed to operator in progress UI.",
    )
    stage_index: Optional[conint(ge=0)] = Field(
        None, description='Optional · stage index in pipeline (0-based).'
    )
    stage_total: Optional[conint(ge=1)] = Field(
        None,
        description='Optional · total stage count in pipeline. stage_index < stage_total.',
    )
    percent: Optional[conint(ge=0, le=100)] = Field(
        None,
        description='Optional · progress percent 0-100 integer (per matrix §3 Q1 decision · NOT float). 100 = stage done.',
    )
    status: Status1 = Field(
        ...,
        description='ProgressMessage status 5-enum (v3 §2.3 line 207 verbatim). DIFFERENT from ToolCall.status 8-enum · ProgressMessage status is stage-level lifecycle (warning = stage degraded but pipeline continues · error = stage fatal · upgrades ToolCall.status to failed at next emit).',
    )
    detail: Optional[str] = Field(
        None,
        description="Optional · free-form detail string (e.g. '已扫 12/45 KB doc'). Shown in progress drawer expandable section.",
    )


class ToolCall(BaseModel):
    """
    Liuye 5-protocol member · ToolCall + ProgressMessage (v3 spec §2.3). Self-describing tool invocation envelope (CC pattern). status fixed at 8 enum · invoker_id/reviewer_id added per P0-8 R9 (audit chain) · parent_tool_call_id links Cowork → Managed handoff. ProgressMessage nested via definitions · its own 5-state status enum (not the 8-state ToolCall.status). ToolDefinition (renderToolCall / inputSchema / outputSchema) is consumer-side TS · NOT modeled here.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1) = Field(
        ...,
        description='ToolCall identifier · unique within a turn. Referenced by Artifact.source_tool_call_id and LiuyeChatEvent.tool_call_id.',
    )
    schema_version: Literal['1'] = Field(
        ...,
        description="Liuye contract schema version · fixed '1' for the current spec lock.",
    )
    turn_id: constr(min_length=1) = Field(
        ...,
        description='Parent conversation turn identifier · same across all events within one user turn.',
    )
    agent: Agent = Field(
        ...,
        description='6-agent enum (v3 §2.3 verbatim · root §4 SSOT). Cowork: channel/credit/report. Managed: alert/compliance/riskctrl.',
    )
    tool_id: constr(min_length=1) = Field(
        ...,
        description='Stable tool identifier · resolves to a ToolDefinition (consumer-side TS · Zod inputSchema/outputSchema).',
    )
    boundary: Boundary = Field(
        ...,
        description='Tool boundary type per root §3.1.1. cowork = real-time SSE (< 5s p95) · managed_readonly = batch (job_id + status + retry).',
    )
    parent_tool_call_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · Cowork → Managed handoff link. Set when this ToolCall was spawned by another ToolCall (e.g. Agent3 cowork credit decision triggers Agent5 managed compliance scan).',
    )
    invoker_id: constr(min_length=1) = Field(
        ...,
        description="P0-8 R9 · the persona/user that triggered this tool_call. Required for audit chain (decision_ledger lookup · LE-05 sign-off). For system-triggered managed jobs (cron / event), set to 'system:<job_kind>'.",
    )
    reviewer_id: Optional[constr(min_length=1)] = Field(
        None,
        description='P0-8 R9 · the reviewer who signed off on this tool_call. Set for LE-05 sign-off / high-risk PermissionRequest approvals. NULL for normal flow.',
    )
    input: Any = Field(
        ...,
        description='Tool input · validated by inputSchema.safeParse() consumer-side (Zod). Open schema here · per-tool narrowing happens at inputSchemas.ts.',
    )
    status: Status = Field(
        ...,
        description='ToolStatus 8-enum lock (v3 §2.3 line 179-181 verbatim · brief §4.2 hardline). Lifecycle: queued → connecting → running → streaming → (completed|failed|aborted|idle_timeout). idle_timeout = no progress emitted within SLA window (per agent SLA · root §3.1.1).',
    )
    progress: List[ProgressMessage] = Field(
        ...,
        description='ProgressMessage list · monotonic seq · emitted via SSE tool.progress events.',
    )
    result: Optional[Any] = Field(
        None,
        description='Tool result · validated by outputSchema consumer-side (Zod). Set when status transitions to completed. Open schema here · per-tool narrowing at inputSchemas.ts.',
    )
    error: Optional[Error] = Field(
        None,
        description='Set when status = failed. Mirrors TurnErrorPayload shape (subset) per liuye_chat_event.schema.json.',
    )
    artifact_id: Optional[constr(min_length=1)] = Field(
        None,
        description='Optional · the Artifact.id produced by this tool_call (Cowork agents only · Managed agents write to decision_ledger instead per root §3.1.1).',
    )
    started_at: AwareDatetime = Field(
        ..., description='ISO 8601 UTC · ToolCall enqueue timestamp.'
    )
    completed_at: Optional[AwareDatetime] = Field(
        None,
        description='ISO 8601 UTC · set when status transitions to completed/failed/aborted/idle_timeout.',
    )

