"""Recovery .bat generator for stuck worker sessions.

Reads mesh.json (and optionally docs/handoff/.watchdog-state.json) and writes
``recovery/restart-<worktree>.bat`` files that the operator can double-click
to spawn a fresh Windows Terminal tab + Claude session in the right worktree.

The generator NEVER auto-executes the .bat — Windows Terminal cannot inject
commands into an existing tab from outside, so the only safe handoff is a
file the human launches manually.

CLI usage:

    py scripts/orchestrator/recovery.py <worktree-name>
    py scripts/orchestrator/recovery.py --all-stuck

Exit codes:

    0  one or more .bat files written
    1  no matching worktrees / nothing to do
    2  usage error
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Mapping, Optional

# orchestrator package lives under scripts/orchestrator/.  Inject scripts/
# onto sys.path so `from orchestrator.lib import mesh` resolves.
_HERE = Path(__file__).resolve()
sys.path.insert(0, str(_HERE.parent.parent))

from orchestrator.lib import mesh  # noqa: E402
from orchestrator.lib.mesh import Mesh, Worktree  # noqa: E402


USAGE = (
    "usage: recovery.py <worktree-name>\n"
    "       recovery.py --all-stuck\n"
)

# Backward-compat alias: the hard-coded proxy fallback is gone (R2). Callers
# that imported DEFAULT_ENV_LINES keep working but get an empty list, which
# is the correct "portable default" now (no hidden machine-specific config).
DEFAULT_ENV_LINES: List[str] = []


def _project_root() -> Path:
    """Resolve project root by walking up from this file (scripts/orchestrator/)."""
    return _HERE.parent.parent.parent


def _read_claude_env_bat(path: Path) -> List[str]:
    """Extract ``set "..."`` lines from a project-local claude-env.bat.

    Returns [] if the file is missing, unreadable, or has no `set` directives.
    This preserves the long-standing project convention without forcing every
    consumer to maintain one.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    out: List[str] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.lower().startswith("set "):
            out.append(stripped)
    return out


def _synthesize_env_lines(environ: Optional[Mapping[str, str]] = None) -> List[str]:
    """Build ``set`` lines from the shell environment.

    Recognised vars (first match wins for proxy):
        MESH_PROXY / http_proxy / HTTPS_PROXY / ALL_PROXY
        CLAUDE_CODE_GIT_BASH_PATH
    Returns [] when nothing relevant is exported, so an un-configured host
    gets a plain ``claude`` invocation with no injected state.
    """
    env = environ if environ is not None else os.environ
    out: List[str] = []
    proxy = (
        env.get("MESH_PROXY")
        or env.get("http_proxy")
        or env.get("HTTPS_PROXY")
        or env.get("https_proxy")
        or env.get("ALL_PROXY")
    )
    if proxy:
        out.append(f'set "https_proxy={proxy}"')
        out.append(f'set "http_proxy={proxy}"')
        out.append(f'set "ALL_PROXY={proxy}"')
    bash = env.get("CLAUDE_CODE_GIT_BASH_PATH")
    if bash:
        out.append(f'set "CLAUDE_CODE_GIT_BASH_PATH={bash}"')
    return out


def build_env_lines(
    claude_env_bat: Optional[Path] = None,
    environ: Optional[Mapping[str, str]] = None,
) -> List[str]:
    """Resolve the ``set`` lines to inject into the spawned shell.

    Precedence (first non-empty wins):
        1. ``scripts/claude-env.bat`` in the project root (explicit opt-in).
        2. Environment variables (see :func:`_synthesize_env_lines`).
        3. Empty list — portable, no hidden machine state.
    """
    if claude_env_bat is None:
        claude_env_bat = _project_root() / "scripts" / "claude-env.bat"
    file_lines = _read_claude_env_bat(claude_env_bat)
    if file_lines:
        return file_lines
    return _synthesize_env_lines(environ)


def _load_env_lines(claude_env_bat: Optional[Path] = None) -> List[str]:
    """Backward-compat wrapper. Prefer :func:`build_env_lines` in new code."""
    return build_env_lines(claude_env_bat=claude_env_bat)


def render_bat(worktree: Worktree, env_lines: List[str]) -> str:
    """Render the .bat content for restarting ``worktree``.

    Pure function — no I/O — so tests can assert on the string directly.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    abs_path = str(worktree.path).replace("/", "\\")
    title = f"claude-{worktree.name}"
    env_chain = " && ".join(env_lines)
    cmd_chain = f"{env_chain} && claude" if env_chain else "claude"
    body = (
        "@echo off\n"
        f"REM Auto-generated by orchestrator/recovery.py at {timestamp}\n"
        f"REM Restart worker session for: {worktree.name} ({worktree.role})\n"
        f"REM Branch: {worktree.branch}\n"
        f"REM Worktree: {abs_path}\n"
        f'wt -w 0 new-tab --title "{title}" -d "{abs_path}" '
        f'-- cmd /k "{cmd_chain}"\n'
    )
    return body


def _write_bat(worktree: Worktree, env_lines: List[str], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"restart-{worktree.name}.bat"
    target.write_text(render_bat(worktree, env_lines), encoding="utf-8")
    return target


def _read_stuck_names(state_path: Path) -> List[str]:
    """Extract worker names whose status starts with ``stuck`` from watchdog state.

    Tolerates several plausible shapes:
      {"workers": {"<name>": {"status": "stuck:..."}}}
      {"<name>": "stuck:..."}
      {"<name>": {"status": "stuck:..."}}
    Returns [] if the file is missing or unparseable.
    """
    if not state_path.exists():
        return []
    try:
        raw = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []

    candidates: dict = {}
    if isinstance(raw, dict) and isinstance(raw.get("workers"), dict):
        candidates = raw["workers"]
    elif isinstance(raw, dict):
        candidates = raw

    stuck: List[str] = []
    for name, payload in candidates.items():
        status: str = ""
        if isinstance(payload, str):
            status = payload
        elif isinstance(payload, dict):
            status = str(payload.get("status", ""))
        if status.lower().startswith("stuck"):
            stuck.append(name)
    return stuck


def _emit(target: Path) -> None:
    sys.stdout.write(f"wrote {target}\n")
    sys.stdout.write("  -> double-click the .bat to spawn a fresh Claude tab\n")


def main(argv: List[str]) -> int:
    if not argv or "-h" in argv or "--help" in argv:
        sys.stdout.write(USAGE)
        return 0 if argv else 2

    m = mesh.load()
    env_lines = build_env_lines()
    out_dir = _project_root() / "recovery"

    if argv[0] == "--all-stuck":
        state_path = _project_root() / "docs" / "handoff" / ".watchdog-state.json"
        stuck_names = _read_stuck_names(state_path)
        if not stuck_names:
            sys.stdout.write(
                f"no stuck workers found (state file: {state_path})\n"
            )
            return 1
        wrote = 0
        for name in stuck_names:
            wt = mesh.find_worktree(m, name)
            if wt is None:
                sys.stderr.write(
                    f"recovery: stuck worker '{name}' not in mesh.json, skipping\n"
                )
                continue
            target = _write_bat(wt, env_lines, out_dir)
            _emit(target)
            wrote += 1
        return 0 if wrote else 1

    if len(argv) != 1:
        sys.stderr.write(USAGE)
        return 2

    name = argv[0]
    wt = mesh.find_worktree(m, name)
    if wt is None:
        sys.stderr.write(
            f"recovery: worktree '{name}' not found in mesh.json\n"
        )
        return 1
    target = _write_bat(wt, env_lines, out_dir)
    _emit(target)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
