"""Recovery .bat generator for stuck worker sessions.

Reads mesh.json (and optionally docs/handoff/.watchdog-state.json) and writes
``recovery/restart-<worktree>.bat`` files that the operator can double-click
to spawn a fresh Windows Terminal tab + Claude session in the right worktree.

The generator NEVER auto-executes the .bat — Windows Terminal cannot inject
commands into an existing tab from outside, so the only safe handoff is a
file the human launches manually.

CLI usage:

    py scripts/orchestrator/recovery.py <worktree-name>
    py scripts/orchestrator/recovery.py --all-stuck

Exit codes:

    0  one or more .bat files written
    1  no matching worktrees / nothing to do
    2  usage error
"""
from __future__ import annotations

import json
import os
import platform
import shlex
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Mapping, Optional, Tuple

# orchestrator package lives under scripts/orchestrator/.  Inject scripts/
# onto sys.path so `from orchestrator.lib import mesh` resolves.
_HERE = Path(__file__).resolve()
sys.path.insert(0, str(_HERE.parent.parent))

from orchestrator.lib import mesh  # noqa: E402
from orchestrator.lib.mesh import Mesh, Worktree  # noqa: E402


USAGE = (
    "usage: recovery.py <worktree-name> [--platform windows|macos|linux]\n"
    "       recovery.py --all-stuck [--platform windows|macos|linux]\n"
)

VALID_PLATFORMS = ("windows", "macos", "linux")

# Backward-compat alias: the hard-coded proxy fallback is gone (R2). Callers
# that imported DEFAULT_ENV_LINES keep working but get an empty list, which
# is the correct "portable default" now (no hidden machine-specific config).
DEFAULT_ENV_LINES: List[str] = []


def _project_root() -> Path:
    """Resolve project root by walking up from this file (scripts/orchestrator/)."""
    return _HERE.parent.parent.parent


def _read_claude_env_bat(path: Path) -> List[str]:
    """Extract ``set "..."`` lines from a project-local claude-env.bat.

    Returns [] if the file is missing, unreadable, or has no `set` directives.
    This preserves the long-standing project convention without forcing every
    consumer to maintain one.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    out: List[str] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.lower().startswith("set "):
            out.append(stripped)
    return out


def _synthesize_env_lines(environ: Optional[Mapping[str, str]] = None) -> List[str]:
    """Build ``set`` lines from the shell environment.

    Recognised vars (first match wins for proxy):
        MESH_PROXY / http_proxy / HTTPS_PROXY / ALL_PROXY
        CLAUDE_CODE_GIT_BASH_PATH
    Returns [] when nothing relevant is exported, so an un-configured host
    gets a plain ``claude`` invocation with no injected state.
    """
    env = environ if environ is not None else os.environ
    out: List[str] = []
    proxy = (
        env.get("MESH_PROXY")
        or env.get("http_proxy")
        or env.get("HTTPS_PROXY")
        or env.get("https_proxy")
        or env.get("ALL_PROXY")
    )
    if proxy:
        out.append(f'set "https_proxy={proxy}"')
        out.append(f'set "http_proxy={proxy}"')
        out.append(f'set "ALL_PROXY={proxy}"')
    bash = env.get("CLAUDE_CODE_GIT_BASH_PATH")
    if bash:
        out.append(f'set "CLAUDE_CODE_GIT_BASH_PATH={bash}"')
    return out


def build_env_lines(
    claude_env_bat: Optional[Path] = None,
    environ: Optional[Mapping[str, str]] = None,
) -> List[str]:
    """Resolve the ``set`` lines to inject into the spawned shell.

    Precedence (first non-empty wins):
        1. ``scripts/claude-env.bat`` in the project root (explicit opt-in).
        2. Environment variables (see :func:`_synthesize_env_lines`).
        3. Empty list — portable, no hidden machine state.
    """
    if claude_env_bat is None:
        claude_env_bat = _project_root() / "scripts" / "claude-env.bat"
    file_lines = _read_claude_env_bat(claude_env_bat)
    if file_lines:
        return file_lines
    return _synthesize_env_lines(environ)


def _load_env_lines(claude_env_bat: Optional[Path] = None) -> List[str]:
    """Backward-compat wrapper. Prefer :func:`build_env_lines` in new code."""
    return build_env_lines(claude_env_bat=claude_env_bat)


def render_bat(worktree: Worktree, env_lines: List[str]) -> str:
    """Render the Windows .bat content for restarting ``worktree``.

    Pure function — no I/O — so tests can assert on the string directly.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    abs_path = str(worktree.path).replace("/", "\\")
    title = f"claude-{worktree.name}"
    env_chain = " && ".join(env_lines)
    cmd_chain = f"{env_chain} && claude" if env_chain else "claude"
    body = (
        "@echo off\n"
        f"REM Auto-generated by orchestrator/recovery.py at {timestamp}\n"
        f"REM Restart worker session for: {worktree.name} ({worktree.role})\n"
        f"REM Branch: {worktree.branch}\n"
        f"REM Worktree: {abs_path}\n"
        f'wt -w 0 new-tab --title "{title}" -d "{abs_path}" '
        f'-- cmd /k "{cmd_chain}"\n'
    )
    return body


# ---- macOS + Linux rendering (R1) -------------------------------------------

def _bash_export(set_line: str) -> str:
    """Convert a Windows ``set "NAME=VAL"`` line to a POSIX ``export NAME='VAL'``.

    Accepts both quoted (``set "K=V"``) and bare (``set K=V``) variants. The
    value is always wrapped in single quotes for POSIX shells so embedded
    ``$`` / backticks / globs stay literal; embedded single quotes are
    escaped using the classic ``'\\''`` sequence.
    """
    if not set_line.lower().startswith("set "):
        return "# (skipped non-set line: " + set_line + ")"
    inner = set_line[4:].strip()
    if inner.startswith('"') and inner.endswith('"') and len(inner) >= 2:
        inner = inner[1:-1]
    if "=" not in inner:
        return "# (skipped malformed set line: " + set_line + ")"
    name, _, val = inner.partition("=")
    safe = val.replace("'", "'\\''")
    return f"export {name.strip()}='{safe}'"


def _bash_env_chain(env_lines: List[str]) -> str:
    """Join env lines into a single ``export ... && export ...`` chain."""
    exports = [_bash_export(line) for line in env_lines]
    exports = [e for e in exports if not e.startswith("#")]
    return " && ".join(exports)


def render_applescript(worktree: Worktree, env_lines: List[str]) -> str:
    """Render a macOS AppleScript that opens Terminal.app + cd + env + claude.

    Run with ``osascript restart-<name>.applescript`` (double-click also works
    after associating the extension).
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    posix_path = str(worktree.path).replace("\\", "/")
    cmd_parts = [f"cd {shlex.quote(posix_path)}"]
    chain = _bash_env_chain(env_lines)
    if chain:
        cmd_parts.append(chain)
    cmd_parts.append("exec claude")
    cmd = " && ".join(cmd_parts)
    # AppleScript string literal: escape backslashes first, then double quotes.
    cmd_escaped = cmd.replace("\\", "\\\\").replace('"', '\\"')
    return (
        f"-- Auto-generated by orchestrator/recovery.py at {timestamp}\n"
        f"-- Restart worker session for: {worktree.name} ({worktree.role})\n"
        f"-- Branch: {worktree.branch}\n"
        f"-- Worktree: {posix_path}\n"
        f"-- Usage: osascript restart-{worktree.name}.applescript\n"
        f'tell application "Terminal"\n'
        f"    activate\n"
        f'    do script "{cmd_escaped}"\n'
        f"end tell\n"
    )


def render_shell_script(worktree: Worktree, env_lines: List[str]) -> str:
    """Render a POSIX shell script that cd's + applies env + execs claude.

    Does NOT spawn a new terminal (Linux desktops vary wildly) — run from your
    existing shell: ``bash restart-<name>.sh``. For tmux users, wrap this
    script in a ``tmux new-window`` call yourself.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    posix_path = str(worktree.path).replace("\\", "/")
    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by orchestrator/recovery.py at {timestamp}",
        f"# Restart worker session for: {worktree.name} ({worktree.role})",
        f"# Branch: {worktree.branch}",
        f"# Worktree: {posix_path}",
        f"# Usage: bash restart-{worktree.name}.sh  (run from your terminal)",
        "set -e",
        f"cd {shlex.quote(posix_path)}",
    ]
    for env_line in env_lines:
        export = _bash_export(env_line)
        lines.append(export)
    lines.append("exec claude")
    return "\n".join(lines) + "\n"


# ---- platform dispatch ------------------------------------------------------

def detect_platform() -> str:
    """Return the current OS tag: ``'windows'`` | ``'macos'`` | ``'linux'``."""
    sys_name = platform.system().lower()
    if sys_name == "windows":
        return "windows"
    if sys_name == "darwin":
        return "macos"
    return "linux"


def render_for_platform(
    worktree: Worktree, env_lines: List[str], target: str
) -> Tuple[str, str]:
    """Render script body + file extension for ``target`` platform.

    Returns ``(body, extension)`` — caller composes the final filename as
    ``restart-<worktree-name><extension>``.
    """
    if target == "windows":
        return render_bat(worktree, env_lines), ".bat"
    if target == "macos":
        return render_applescript(worktree, env_lines), ".applescript"
    if target == "linux":
        return render_shell_script(worktree, env_lines), ".sh"
    raise ValueError(
        f"unknown platform {target!r}; expected one of {VALID_PLATFORMS}"
    )


def _write_bat(worktree: Worktree, env_lines: List[str], out_dir: Path) -> Path:
    """Backward-compat thin wrapper: always renders the Windows .bat flavour."""
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"restart-{worktree.name}.bat"
    target.write_text(render_bat(worktree, env_lines), encoding="utf-8")
    return target


def _write_script(
    worktree: Worktree,
    env_lines: List[str],
    out_dir: Path,
    target_platform: str,
) -> Path:
    """Render + write the platform-appropriate restart script."""
    out_dir.mkdir(parents=True, exist_ok=True)
    body, ext = render_for_platform(worktree, env_lines, target_platform)
    target = out_dir / f"restart-{worktree.name}{ext}"
    target.write_text(body, encoding="utf-8")
    # Best-effort chmod +x for posix flavours; harmless on Windows.
    if target_platform in ("macos", "linux"):
        try:
            mode = target.stat().st_mode
            target.chmod(mode | 0o111)
        except OSError:
            pass
    return target


def _read_stuck_names(state_path: Path) -> List[str]:
    """Extract worker names whose status starts with ``stuck`` from watchdog state.

    Tolerates several plausible shapes:
      {"workers": {"<name>": {"status": "stuck:..."}}}
      {"<name>": "stuck:..."}
      {"<name>": {"status": "stuck:..."}}
    Returns [] if the file is missing or unparseable.
    """
    if not state_path.exists():
        return []
    try:
        raw = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []

    candidates: dict = {}
    if isinstance(raw, dict) and isinstance(raw.get("workers"), dict):
        candidates = raw["workers"]
    elif isinstance(raw, dict):
        candidates = raw

    stuck: List[str] = []
    for name, payload in candidates.items():
        status: str = ""
        if isinstance(payload, str):
            status = payload
        elif isinstance(payload, dict):
            status = str(payload.get("status", ""))
        if status.lower().startswith("stuck"):
            stuck.append(name)
    return stuck


def _emit(target: Path, platform_tag: str) -> None:
    sys.stdout.write(f"wrote {target}\n")
    if platform_tag == "windows":
        sys.stdout.write("  -> double-click the .bat to spawn a fresh Claude tab\n")
    elif platform_tag == "macos":
        sys.stdout.write(
            "  -> run `osascript " + target.name + "` to spawn a Terminal window\n"
        )
    else:
        sys.stdout.write(
            "  -> run `bash " + target.name + "` in your preferred terminal\n"
        )


def _pop_platform(argv: List[str]) -> str:
    """Extract --platform <target> from argv in place, default to host OS."""
    if "--platform" in argv:
        idx = argv.index("--platform")
        if idx + 1 >= len(argv):
            sys.stderr.write("recovery: --platform requires a value\n")
            sys.exit(2)
        value = argv[idx + 1]
        del argv[idx:idx + 2]
        if value not in VALID_PLATFORMS:
            sys.stderr.write(
                f"recovery: unknown platform {value!r}; "
                f"expected one of {VALID_PLATFORMS}\n"
            )
            sys.exit(2)
        return value
    return detect_platform()


def main(argv: List[str]) -> int:
    args = list(argv)
    if not args or "-h" in args or "--help" in args:
        sys.stdout.write(USAGE)
        return 0 if args else 2

    target_platform = _pop_platform(args)
    if not args:
        sys.stderr.write(USAGE)
        return 2

    m = mesh.load()
    env_lines = build_env_lines()
    out_dir = _project_root() / "recovery"

    if args[0] == "--all-stuck":
        state_path = _project_root() / "docs" / "handoff" / ".watchdog-state.json"
        stuck_names = _read_stuck_names(state_path)
        if not stuck_names:
            sys.stdout.write(
                f"no stuck workers found (state file: {state_path})\n"
            )
            return 1
        wrote = 0
        for name in stuck_names:
            wt = mesh.find_worktree(m, name)
            if wt is None:
                sys.stderr.write(
                    f"recovery: stuck worker '{name}' not in mesh.json, skipping\n"
                )
                continue
            target = _write_script(wt, env_lines, out_dir, target_platform)
            _emit(target, target_platform)
            wrote += 1
        return 0 if wrote else 1

    if len(args) != 1:
        sys.stderr.write(USAGE)
        return 2

    name = args[0]
    wt = mesh.find_worktree(m, name)
    if wt is None:
        sys.stderr.write(
            f"recovery: worktree '{name}' not found in mesh.json\n"
        )
        return 1
    target = _write_script(wt, env_lines, out_dir, target_platform)
    _emit(target, target_platform)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
