"""Recovery .bat generator for stuck worker sessions.

Reads mesh.json (and optionally docs/handoff/.watchdog-state.json) and writes
``recovery/restart-<worktree>.bat`` files that the operator can double-click
to spawn a fresh Windows Terminal tab + Claude session in the right worktree.

The generator NEVER auto-executes the .bat — Windows Terminal cannot inject
commands into an existing tab from outside, so the only safe handoff is a
file the human launches manually.

CLI usage:

    py scripts/orchestrator/recovery.py <worktree-name>
    py scripts/orchestrator/recovery.py --all-stuck

Exit codes:

    0  one or more .bat files written
    1  no matching worktrees / nothing to do
    2  usage error
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

# orchestrator package lives under scripts/orchestrator/.  Inject scripts/
# onto sys.path so `from orchestrator.lib import mesh` resolves.
_HERE = Path(__file__).resolve()
sys.path.insert(0, str(_HERE.parent.parent))

from orchestrator.lib import mesh  # noqa: E402
from orchestrator.lib.mesh import Mesh, Worktree  # noqa: E402


USAGE = (
    "usage: recovery.py <worktree-name>\n"
    "       recovery.py --all-stuck\n"
)

# Mirrors scripts/claude-env.bat — inlined into the cmd /k chain so the
# spawned shell sees proxy + Git Bash settings without sourcing a helper.
DEFAULT_ENV_LINES: List[str] = [
    'set "https_proxy=http://127.0.0.1:7897"',
    'set "http_proxy=http://127.0.0.1:7897"',
    'set "ALL_PROXY=http://127.0.0.1:7897"',
    'set "CLAUDE_CODE_GIT_BASH_PATH=D:\\Git\\usr\\bin\\bash.exe"',
]


def _project_root() -> Path:
    """Resolve project root by walking up from this file (scripts/orchestrator/)."""
    return _HERE.parent.parent.parent


def _load_env_lines(claude_env_bat: Optional[Path] = None) -> List[str]:
    """Read the four ``set "..."`` lines from scripts/claude-env.bat.

    Falls back to DEFAULT_ENV_LINES if the helper file is missing or
    unreadable, so recovery still works on a freshly-cloned worktree.
    """
    if claude_env_bat is None:
        claude_env_bat = _project_root() / "scripts" / "claude-env.bat"
    try:
        text = claude_env_bat.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return list(DEFAULT_ENV_LINES)
    lines: List[str] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.lower().startswith("set "):
            lines.append(stripped)
    return lines or list(DEFAULT_ENV_LINES)


def render_bat(worktree: Worktree, env_lines: List[str]) -> str:
    """Render the .bat content for restarting ``worktree``.

    Pure function — no I/O — so tests can assert on the string directly.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    abs_path = str(worktree.path).replace("/", "\\")
    title = f"claude-{worktree.name}"
    env_chain = " && ".join(env_lines)
    cmd_chain = f"{env_chain} && claude" if env_chain else "claude"
    body = (
        "@echo off\n"
        f"REM Auto-generated by orchestrator/recovery.py at {timestamp}\n"
        f"REM Restart worker session for: {worktree.name} ({worktree.role})\n"
        f"REM Branch: {worktree.branch}\n"
        f"REM Worktree: {abs_path}\n"
        f'wt -w 0 new-tab --title "{title}" -d "{abs_path}" '
        f'-- cmd /k "{cmd_chain}"\n'
    )
    return body


def _write_bat(worktree: Worktree, env_lines: List[str], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"restart-{worktree.name}.bat"
    target.write_text(render_bat(worktree, env_lines), encoding="utf-8")
    return target


def _read_stuck_names(state_path: Path) -> List[str]:
    """Extract worker names whose status starts with ``stuck`` from watchdog state.

    Tolerates several plausible shapes:
      {"workers": {"<name>": {"status": "stuck:..."}}}
      {"<name>": "stuck:..."}
      {"<name>": {"status": "stuck:..."}}
    Returns [] if the file is missing or unparseable.
    """
    if not state_path.exists():
        return []
    try:
        raw = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []

    candidates: dict = {}
    if isinstance(raw, dict) and isinstance(raw.get("workers"), dict):
        candidates = raw["workers"]
    elif isinstance(raw, dict):
        candidates = raw

    stuck: List[str] = []
    for name, payload in candidates.items():
        status: str = ""
        if isinstance(payload, str):
            status = payload
        elif isinstance(payload, dict):
            status = str(payload.get("status", ""))
        if status.lower().startswith("stuck"):
            stuck.append(name)
    return stuck


def _emit(target: Path) -> None:
    sys.stdout.write(f"wrote {target}\n")
    sys.stdout.write("  -> double-click the .bat to spawn a fresh Claude tab\n")


def main(argv: List[str]) -> int:
    if not argv or "-h" in argv or "--help" in argv:
        sys.stdout.write(USAGE)
        return 0 if argv else 2

    m = mesh.load()
    env_lines = _load_env_lines()
    out_dir = _project_root() / "recovery"

    if argv[0] == "--all-stuck":
        state_path = _project_root() / "docs" / "handoff" / ".watchdog-state.json"
        stuck_names = _read_stuck_names(state_path)
        if not stuck_names:
            sys.stdout.write(
                f"no stuck workers found (state file: {state_path})\n"
            )
            return 1
        wrote = 0
        for name in stuck_names:
            wt = mesh.find_worktree(m, name)
            if wt is None:
                sys.stderr.write(
                    f"recovery: stuck worker '{name}' not in mesh.json, skipping\n"
                )
                continue
            target = _write_bat(wt, env_lines, out_dir)
            _emit(target)
            wrote += 1
        return 0 if wrote else 1

    if len(argv) != 1:
        sys.stderr.write(USAGE)
        return 2

    name = argv[0]
    wt = mesh.find_worktree(m, name)
    if wt is None:
        sys.stderr.write(
            f"recovery: worktree '{name}' not found in mesh.json\n"
        )
        return 1
    target = _write_bat(wt, env_lines, out_dir)
    _emit(target)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
