"""Mesh Scoreboard · render markdown status table for all worktrees.

Usage:
    py scripts/orchestrator/scoreboard.py            # stdout
    py scripts/orchestrator/scoreboard.py --write    # also write docs/handoff/scoreboard.md
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# scripts/orchestrator/scoreboard.py -> add scripts/ to sys.path so `orchestrator.lib` imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from orchestrator.lib import git_helpers, mesh  # noqa: E402


SIGNAL_RE = re.compile(r"Signal:\s*(.+?)\s*$", re.MULTILINE)


# ---------- pure helpers (testable) ----------

def format_age(seconds: Optional[int]) -> str:
    """Format an age in seconds as 'Nm ago' / 'Nh ago' / 'Nd ago'. None -> '-'."""
    if seconds is None:
        return "-"
    if seconds < 0:
        seconds = 0
    if seconds < 3600:
        return f"{seconds // 60}m ago"
    if seconds < 86400:
        return f"{seconds // 3600}h ago"
    return f"{seconds // 86400}d ago"


def status_emoji(seconds: Optional[int], head_present: bool) -> str:
    """Map commit age to status emoji.

    Rules:
      - unknown (no HEAD): black circle
      - < 4h:    green
      - < 7d:    yellow
      - >= 7d:   red
    """
    if not head_present or seconds is None:
        return "\U000026AB unknown"  # black circle
    if seconds < 4 * 3600:
        return "\U0001F7E2 fresh"  # green circle
    if seconds < 7 * 86400:
        return "\U0001F7E1 idle"  # yellow circle
    return "\U0001F534 stale"  # red circle


def extract_signal(commit_body: Optional[str]) -> Optional[str]:
    """Extract `Signal: <name>` from a commit body."""
    if not commit_body:
        return None
    m = SIGNAL_RE.search(commit_body)
    if m:
        return m.group(1).strip()
    return None


# ---------- rendering ----------

def render_row(w) -> str:
    """Render one worktree row. Triple git call (head_sha + age + signal)."""
    sha = git_helpers.head_sha(w.path)
    if sha is None:
        # git unreachable — degrade gracefully
        return (
            f"| {w.name} | {w.role} | `{w.branch}` | - | - | - | "
            f"{status_emoji(None, head_present=False)} |"
        )

    subject = git_helpers.head_subject(w.path) or ""
    age = git_helpers.commit_age_seconds(w.path)
    signal_commit = git_helpers.last_commit_with_signal(w.path)

    # Signal can live in body OR subject (mirrors last_commit_with_signal logic)
    signal_name: Optional[str] = None
    if signal_commit is not None:
        signal_name = extract_signal(signal_commit.body) or extract_signal(
            signal_commit.subject
        )

    short_sha = sha[:7]
    head_cell = f"`{short_sha}` {_truncate(subject, 48)}"
    signal_cell = signal_name or "-"
    age_cell = format_age(age)
    status_cell = status_emoji(age, head_present=True)

    return (
        f"| {w.name} | {w.role} | `{w.branch}` | {head_cell} | "
        f"{signal_cell} | {age_cell} | {status_cell} |"
    )


def _truncate(s: str, n: int) -> str:
    if len(s) <= n:
        return s
    return s[: n - 1] + "…"


def render_scoreboard(m) -> str:
    now = datetime.now(timezone.utc).astimezone()
    iso = now.isoformat(timespec="seconds")
    human = now.strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"<!-- generated by orchestrator/scoreboard.py at {iso} -->",
        "# Mesh Scoreboard",
        "",
        f"**Project**: {m.project} · **Worktrees**: {len(m.worktrees)} · **Last update**: {human}",
        "",
        "| Worktree | Role | Branch | HEAD | Last Signal | Last Activity | Status |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for w in m.worktrees:
        lines.append(render_row(w))
    lines.append("")  # trailing newline
    return "\n".join(lines)


# ---------- CLI ----------

def main() -> int:
    parser = argparse.ArgumentParser(description="Render mesh scoreboard.")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Also write to docs/handoff/scoreboard.md (in addition to stdout).",
    )
    args = parser.parse_args()

    m = mesh.load()
    rendered = render_scoreboard(m)
    print(rendered)

    if args.write:
        # mesh.load() found mesh.json by walking up; resolve sibling scoreboard.md
        # by re-using the same lookup heuristic.
        cur = Path.cwd().resolve()
        out_path: Optional[Path] = None
        for _ in range(20):
            candidate = cur / "docs" / "handoff"
            if (candidate / "mesh.json").exists():
                out_path = candidate / "scoreboard.md"
                break
            if cur.parent == cur:
                break
            cur = cur.parent
        if out_path is None:
            print("[scoreboard] could not locate docs/handoff/ to write", file=sys.stderr)
            return 1
        out_path.write_text(rendered, encoding="utf-8")
        print(f"\n[scoreboard] wrote {out_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
