"""Mesh Scoreboard · render markdown status table + structured JSON for all worktrees.

Usage:
    py scripts/orchestrator/scoreboard.py                          # markdown to stdout
    py scripts/orchestrator/scoreboard.py --write                  # also write docs/handoff/scoreboard.md
    py scripts/orchestrator/scoreboard.py --json-write             # also write docs/handoff/mesh-status.json
    py scripts/orchestrator/scoreboard.py --out-json <PATH>        # write JSON to specific path
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

# scripts/orchestrator/scoreboard.py -> add scripts/ to sys.path so `orchestrator.lib` imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from orchestrator.lib import git_helpers, mesh  # noqa: E402


SIGNAL_RE = re.compile(r"Signal:\s*(.+?)\s*$", re.MULTILINE)


# ---------- pure helpers (testable) ----------

def format_age(seconds: Optional[int]) -> str:
    """Format an age in seconds as 'Nm ago' / 'Nh ago' / 'Nd ago'. None -> '-'."""
    if seconds is None:
        return "-"
    if seconds < 0:
        seconds = 0
    if seconds < 3600:
        return f"{seconds // 60}m ago"
    if seconds < 86400:
        return f"{seconds // 3600}h ago"
    return f"{seconds // 86400}d ago"


def status_emoji(seconds: Optional[int], head_present: bool) -> str:
    """Map commit age to status emoji.

    Rules:
      - unknown (no HEAD): black circle
      - < 4h:    green
      - < 7d:    yellow
      - >= 7d:   red
    """
    if not head_present or seconds is None:
        return "\U000026AB unknown"  # black circle
    if seconds < 4 * 3600:
        return "\U0001F7E2 fresh"  # green circle
    if seconds < 7 * 86400:
        return "\U0001F7E1 idle"  # yellow circle
    return "\U0001F534 stale"  # red circle


def extract_signal(commit_body: Optional[str]) -> Optional[str]:
    """Extract `Signal: <name>` from a commit body."""
    if not commit_body:
        return None
    m = SIGNAL_RE.search(commit_body)
    if m:
        return m.group(1).strip()
    return None


# ---------- rendering ----------

def render_row(w) -> str:
    """Render one worktree row. Triple git call (head_sha + age + signal)."""
    sha = git_helpers.head_sha(w.path)
    if sha is None:
        # git unreachable — degrade gracefully
        return (
            f"| {w.name} | {w.role} | `{w.branch}` | - | - | - | "
            f"{status_emoji(None, head_present=False)} |"
        )

    subject = git_helpers.head_subject(w.path) or ""
    age = git_helpers.commit_age_seconds(w.path)
    signal_commit = git_helpers.last_commit_with_signal(w.path)

    # Signal can live in body OR subject (mirrors last_commit_with_signal logic)
    signal_name: Optional[str] = None
    if signal_commit is not None:
        signal_name = extract_signal(signal_commit.body) or extract_signal(
            signal_commit.subject
        )

    short_sha = sha[:7]
    head_cell = f"`{short_sha}` {_truncate(subject, 48)}"
    signal_cell = signal_name or "-"
    age_cell = format_age(age)
    status_cell = status_emoji(age, head_present=True)

    return (
        f"| {w.name} | {w.role} | `{w.branch}` | {head_cell} | "
        f"{signal_cell} | {age_cell} | {status_cell} |"
    )


def _truncate(s: str, n: int) -> str:
    if len(s) <= n:
        return s
    return s[: n - 1] + "…"


def render_scoreboard(m) -> str:
    now = datetime.now(timezone.utc).astimezone()
    iso = now.isoformat(timespec="seconds")
    human = now.strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"<!-- generated by orchestrator/scoreboard.py at {iso} -->",
        "# Mesh Scoreboard",
        "",
        f"**Project**: {m.project} · **Worktrees**: {len(m.worktrees)} · **Last update**: {human}",
        "",
        "| Worktree | Role | Branch | HEAD | Last Signal | Last Activity | Status |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for w in m.worktrees:
        lines.append(render_row(w))
    lines.append("")  # trailing newline
    return "\n".join(lines)


# ---------- structured JSON for cc_monitor / external consumers ----------

@dataclass
class WorktreeRecord:
    name: str
    role: str
    branch: str
    path: str
    head_sha: Optional[str]
    head_short: Optional[str]
    head_subject: Optional[str]
    last_signal: Optional[str]
    age_seconds: Optional[int]
    age_human: str
    status: str       # "fresh" / "idle" / "stale" / "unknown"
    status_emoji: str


def collect_record(w) -> WorktreeRecord:
    """Collect one worktree's full state into a structured record. Triple git call."""
    sha = git_helpers.head_sha(w.path)
    if sha is None:
        return WorktreeRecord(
            name=w.name, role=w.role, branch=w.branch, path=str(w.path),
            head_sha=None, head_short=None, head_subject=None,
            last_signal=None, age_seconds=None, age_human="-",
            status="unknown", status_emoji="\U000026AB",
        )

    subject = git_helpers.head_subject(w.path) or ""
    age = git_helpers.commit_age_seconds(w.path)
    sig_commit = git_helpers.last_commit_with_signal(w.path)
    last_sig: Optional[str] = None
    if sig_commit is not None:
        last_sig = extract_signal(sig_commit.body) or extract_signal(sig_commit.subject)

    if age is None:
        status, emoji = "unknown", "\U000026AB"
    elif age < 4 * 3600:
        status, emoji = "fresh", "\U0001F7E2"
    elif age < 7 * 86400:
        status, emoji = "idle", "\U0001F7E1"
    else:
        status, emoji = "stale", "\U0001F534"

    return WorktreeRecord(
        name=w.name, role=w.role, branch=w.branch, path=str(w.path),
        head_sha=sha, head_short=sha[:7], head_subject=subject,
        last_signal=last_sig, age_seconds=age, age_human=format_age(age),
        status=status, status_emoji=emoji,
    )


def collect_all(m) -> List[WorktreeRecord]:
    return [collect_record(w) for w in m.worktrees]


def render_json_payload(m) -> str:
    """Render structured JSON consumable by cc_monitor + external dashboards."""
    records = collect_all(m)
    summary = {"fresh": 0, "idle": 0, "stale": 0, "unknown": 0}
    for r in records:
        summary[r.status] = summary.get(r.status, 0) + 1
    payload = {
        "schema_version": 1,
        "timestamp": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
        "project": m.project,
        "protocol_version": m.protocol_version,
        "worktree_count": len(records),
        "summary": summary,
        "worktrees": [asdict(r) for r in records],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _resolve_handoff_dir() -> Optional[Path]:
    """Walk up from cwd to find docs/handoff/ (sibling of mesh.json)."""
    cur = Path.cwd().resolve()
    for _ in range(20):
        candidate = cur / "docs" / "handoff"
        if (candidate / "mesh.json").exists():
            return candidate
        if cur.parent == cur:
            break
        cur = cur.parent
    return None


# ---------- CLI ----------

def _ensure_utf8_stdout() -> None:
    """Force stdout to UTF-8 on Windows (default GBK chokes on emoji)."""
    enc = (sys.stdout.encoding or "").lower()
    if enc != "utf-8":
        try:
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def main() -> int:
    _ensure_utf8_stdout()

    parser = argparse.ArgumentParser(description="Render mesh scoreboard.")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Also write to docs/handoff/scoreboard.md (in addition to stdout).",
    )
    parser.add_argument(
        "--json-write",
        action="store_true",
        help="Also write structured JSON to docs/handoff/mesh-status.json.",
    )
    parser.add_argument(
        "--out-json",
        metavar="PATH",
        help="Write structured JSON to PATH (overrides --json-write default location).",
    )
    args = parser.parse_args()

    m = mesh.load()
    rendered = render_scoreboard(m)
    print(rendered)

    if args.write:
        d = _resolve_handoff_dir()
        if d is None:
            print("[scoreboard] could not locate docs/handoff/ to write", file=sys.stderr)
            return 1
        out_path = d / "scoreboard.md"
        out_path.write_text(rendered, encoding="utf-8")
        print(f"\n[scoreboard] wrote {out_path}", file=sys.stderr)

    if args.json_write or args.out_json:
        if args.out_json:
            json_path = Path(args.out_json)
        else:
            d = _resolve_handoff_dir()
            if d is None:
                print("[scoreboard] could not locate docs/handoff/ for JSON", file=sys.stderr)
                return 1
            json_path = d / "mesh-status.json"
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(render_json_payload(m), encoding="utf-8")
        print(f"[scoreboard] wrote {json_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
